= Betriebsdokumentation

== Systemvoraussetzungen

=== Mindestanforderungen an Hardware

* Ein internetfähiges Gerät (Smartphone, Tablet, PC) für die Nutzung der Anwendung

* PC/Server mit Docker und Git

* Für Docker: link:https://docs.docker.com/desktop/windows/install/[Windows], link:https://docs.docker.com/desktop/linux/install/[Linux], link:https://docs.docker.com/desktop/mac/install/[Mac]

=== Softwareanforderungen

* Aktueller Webbrowser (Chrome Ver. 102.0.5005.115 oder höher, Safari Ver. 15.5 oder höher) mit HTML5- und Javascript Unterstützung
* Docker Compose Ver. 3.3 oder höher

=== Systemeinrichtung 

Die Software ist eine webbasierte Anwendung, die sich in einem öffentlichen Repository auf GitHub befindet (link:https://github.com/PowerOfCreation/E1Ressourcenverwaltung[Link]). Die Anwendung besteht aus mehreren Ordnern und Komponenten wie PHP-Dateien, die durch CSS- und JS-Dateien ergänzt werden. 

Bevor mit der Installation fortgefahren wird, ist es empfehlenswert, einen Fork vom Repository zu erzeugen und im eigenen Account abzuspeichern. 

Im Terminal:

`$ git fork https://github.com/PowerOfCreation/E1Ressourcenverwaltung.git`

Um die Software von GitHub auf Ihren eigenen PC/Server zu speichern, muss diese zuerst von GitHub geladen werden.

`$ git clone https://github.com/ihr_github_account/E1Ressourcenverwaltung.git`

Die Software besteht aus zwei serverseitigen Komponenten: Apache Webserver 8.0 und MySQL (MariaDB Ver. 10.3.27 für Alpine Linux), die in einem Docker-Container gespeichert sind.

Um die Software zu installieren, soll ein Docker Container ausgeführt werden. Dafür gibt es zwei Möglichkeiten:

* Im Ordner "src" die Datei "docker-compose.yml" per Drag and Drop in den Docker Desktop schieben und anschließend auf "Start" drücken. -> Diese Vorgehensweise funktioniert nur unter Windows/Mac

* Im Terminal den Ordner "src" wählen und im Anschluss mit dem Befehl "docker-compose up" die Software ausführen (Docker muss gestartet sein):


1. Zum Ordner navigieren:

 $ cd pfad/zum/Ordner/E1Ressourcenverwaltung

2. In Unterordner wechseln:

 $ cd src

3. Server starten:

 ** Für neuere Docker Versionen:

 $ docker compose up

 ** Für ältere Docker Versionen:

 $ docker-compose up

Die Software ist out of the box einsatzbereit, das bedeutet es müssen keine weiteren Konfigurationen vorgenommen werden. 

Um zu überprüfen, ob die Anwendung funktioniert, soll im Webbrowser in der Adresszeile "localhost" eingegeben werden. Daraufhin wird die Login-Seite geöffnet.

Die Software wird mit einem Default-Benutzerkonto mitgeliefert:

`Nutzername: Testnutzer`

`Passwort: 12345678!`

Nach dem ersten Login soll ein eigenes Benutzerkonto erstellt und der Testnutzer gelöscht werden. Falls alle Benutzerkonten gelöscht werden, wird automatisch das Konto "Testnutzer" wieder angelegt. Somit besteht immer die Möglichkeit, sich in der Anwendung anzumelden. 

Die Software soll aus Sicherheitsgründen ausschließlich im Intranet verwendet werden, weil Daten nicht verschlüsselt übertragen werden und es eine Gefahr von Man-in-the-Middle-Attack besteht. Für die Nutzung im Internet soll ein SSL-Zertifikat erstellt werden. 

== Fehlerbehebung

Die meisten Fehler, die auftreten können, werden mit dem Programm Docker zusammenhängen. 

Die typischen Fehler und deren Behebung finden Sie unter folgendem Link:

* link:https://docs.docker.com/desktop/windows/troubleshoot/[Docker Troubleshoot]


== Weitere Dokumentationen

* link:https://docs.docker.com/desktop/[Docker]
* link:https://httpd.apache.org/docs/[Apache Webserver]
* link:https://mariadb.com/kb/en/documentation/[MariaDB]