//AKTUELL SIND ES NUR STICHPUNKTE/GEDANKENSTÜTZEN WAS HIER BEHANDELT WERDEN SOLL

//Problem: aufgaben wurden erstellt und vergeben dann wurden die zwar angefangen zu bearbeiten aber nicht beendet

//weiterhin haben wir/ich bei den programmieraufgaben im Iterationsplan oft "weitere funktionen" geschrieben, aber nicht was genau getan wurde
//das kann zwar mithilfe der issues etwas nachverfolgt werden, aber auch nicht perfekt, da die manchmal erstellt aber nicht assignet wurden 

= Projektdurchführung


== I09

Iteration 9 (23.03.22 - 28.03.22)war die erste Iteration im neuen Semester. Wir hatten wegen der Semesterferien fast 2 Monate nicht mehr an dem Projekt gearbeitet. Daher mussten wir uns erst einmal wieder einen Überblick über den aktuellen Stand verschaffen und unsere Fähigkeiten aus dem Winterschlaf holen. 
//passt der joke oder soll das raus?
Nicht passend dafür war der krankheitsbedingte Ausfall von Herrn Keil und Frau Tartz, diese sollen noch weitere Wochen ausfallen. 
//risiko 

Unsere Ziele für I09 waren: 
Neubegonnen:
-Nutzerübersichtsseite #39
-Datenbanktabelle für Beziehung zwischen Projekt und Benutzer #38
-Mitarbeiter anlegen um Abteilungsdropdown erweitern #35 
//wurde erst später beendet, aber naja
-Aufräumen der Datenbankenstruktur #37
-Anlegen der Abteilungstabelle + 5 Abteilungen #34
-Mitarbeiter hinzufügen check der E-Mail #33
-Mitarbeiter hinzufügen Passwortkriterien #36
//später nochmal geöffnet
//-Praktikumsfragen #31  
//da war doch ein coach treffen oder? ja am 22.4
-Beleg korrigieren #29

//andere Reihenfolge und ohne #
//überschriften?


=== Dokumentation

Wie bereits geschrieben, hat Herr Anke hat unseren abgegeben Beleg über die Semesterferien korrigiert. Auch wenn es nicht viele Fehler gab, mussten diese natürlich korrigiert werden. 
Manche Fehler waren schlechter Ausdruck oder es es fehlten Kleinigkeiten bei sonst korrektem Inhalt. Dies konnte schnell behoben werden. 

Die schwerwiegerenden Fehler waren die komplett falsche "logische Sicht". Dort wurde mit einem C4-Modell gerechnet, welches wir jedoch nicht hatten. Daher musste dieses von Grund auf erstellt werden. Da das Back-End zu dem Zeitpunkt noch nicht komplett fertig war, wurden erst einmal die beiden oberen Sichten angefertigt. Eventuelle weitere Sichten sollten möglicherweise im weiterem Verlauf des Projekts folgen. 
//nennt man das Sichten?
Außerdem fehlte der komplette Abschnitt "Praktiken und Bewertung". Diese Aufgabe war nicht unbedingt schwierig, jedoch war es viel daher konnte die Bearbeitung nicht in dieser Iteration beendet werden.


=== Implementation


Die Datenbank musste aktualisiert werden, damit weitere Funktionen realisiert werden können.
Die beiden Aufgaben konnten ohne Probleme beendet werden. (#34 und #38)

UC3
Herr Liebert wollte eine Übersicht über einen Benutzer haben, wenn dieser in der Kalenderübersicht angeklickt wird. Dort sollte Name, Abteilung und Lösch- sowie Bearbeitungsmöglichkeiten des Mitarbeiters angezeigt werden. Da wir keine Button ohne direkt geplante Funktion haben wollte, wurde der Lösch- und Bearbeitungsbutton nicht umgesetzt und war daher für später geplant. (#39)
//bild einfügen

Natürlich soll wenn ein neuer Mitarbeiter angelegt wird, eine Email erstellt werden, welche zumindest den formalen Anforderungen an eine Email entspricht. Dies wurde erledigt. (#33)
//das wurde beendet oder?
Ebenso soll das verwendete Passwort minimalen Sicherheitsstandards entsprechen.
Da das RegEx und der zugehörige PHP-Code nicht besonders einfach ist und dieses Issue nicht die höchste priorität hatte, konnte es erst später beendet werden. #36
//stimmt das so?
Bei der Erstellung soll die Abteilung des Mitarbeiters aus einem Dropdown-Menü auswählbar sein. Dies stellte kein Problem dar. 

=== Entscheidungen:

Zu diesem Zeitpunkt fehlten Herr Keil und Frau Tartz bei dem wöchentlichen Teammeeting. Wir entschieden uns noch keine "Maßnahmen" zu treffen, da dies auch einfach eine normale Krankheit bzw. anderweitige terminliche Schwierigkeit sein konnte.

== Iteration 10  
29.03.22 - 04.04.22
//wo sind hier die aufgaben, als ob nichts neues begonnen wurden ist
Unsere Ziele für I10 waren: 
Neubegonnen:
Suche implementieren #28 -> nie von jonas keil angefangen und auch nicht wichtig genug, das es weitergeführt wird, da kräfte gesammelt werden mussten

Mehr Dummy-Daten für Project und Project_User #42 -> assigned aber nie begonnen erst am 25.4

Fortgeführt: 
Beleg korrigieren #29
Mitarbeiter hinzufügen Passwortkriterien #36

=== Implementation

Es sollte eine simple Suchfunktion eingefügt werden, sodass nach Mitarbeiter und Projekten gesucht werden kann und bloß diese Angezeigt werden. Diese Aufgabe wurde Herr Keil in Abwesenheit gegeben.
//das hat kein direkten use case
UC 03
Es sollten Dummy-Daten für Projekte eingefügt, damit damit gleich die Funktionaltität überprüft werden konnte und das spätere Arbeiten angenehmer gestaltete. Jedoch wurde dies nie begonnen und daher in der nächsten Iteration fortgeführt.

Leider konnten die Passwortkriterien-Aufgabe immer noch nicht abgeschlossen werden. 


== Problem

Es wurden kaum neue Aufgaben vergeben, zeitgleich gab es aber auch kaum alte zum fortführen. Hier wurde das 1. Mal gemerkt, dass das Projekt zu stocken beginnt. Jedoch hatten wir die Hoffnung, dass dies in der nächsten Iteration besser wird.
//was hatte das für einen Grund und wieso war das in der nächsten woche noch einmal 

== Iteraion 11 05.04.22. - 11.04.22
Unsere Ziele für I11 waren: 
//wo sind hier die aufgaben, als ob nichts neues begonnen/fortgeführt wurden ist
Neubegonnen:  -Erstellen des Status soll nur noch mit einem gültigen Projektnamen funktionieren #30
Projekterstellungsseite Frontend+Backend #32
Fortgeführt:
Beleg korrigieren #29
Mitarbeiter hinzufügen Passwortkriterien #36
Mehr Dummy-Daten für Project und Project_User #42

=== Dokumentation

Die restlichen Fehler bzw. Ungenauigkeiten des Belegs konnten behoben werden. Dazu zählten Praktiken und Bewertung, sowie das C4-Model.

=== Implementaton

UC 03
Wenn ein Projekt angelegt wird, sollte dies bloß noch mit einem eingetragenen Namen möglich sein. 

Dieses Mal konnten die Dummy-Daten eingefügt werden.

== Iteration12 12.04.22-25.04.22
In dieser Iteration wurden endlich wieder neue Aufgaben begonnen und wir bekammen ein neues Mitglied, welches im Front-End und Back-End gut bewandert war. Dies war eine nötige Verstärkung für uns, da wir sonst gefahr liefen, dass wir aufgrund von "nicht wissen" nicht weiter bzw. langsam vorankommen (risiko)
Unsere Ziele für I12 waren: 
Neubegonnen: 
    Beleg aktuell halten bzw. weiterbearbeiten #41  -> dauerauftrag
    Projekterstellungsseite Frontend+Backend #32
    Mehr Dummy-Daten für Project und Project_User #42 -> nicht geschafft und dann neu vergeben an carl
    API: Aktuelle Kalenderwoche #43 -> fertig
    Projektverwaltungsseite #45 -> angefangen aber nicht fertig, daher später weitergemacht 
    Neues Mitglied Vinh einführen
Fortgeführt:
=== Dokumentation

Da der Beleg aktuell war, musste bloß unser neues Mitglied Vinh Nguyen in die Dokumentation eingetragen und darin geschult werden, damit er damit umgehen kann.

=== Implementation

UC 04
Elementarer Bestandteil des SEII-Projekts war es, dass Projekte angelegt werden können. Das Projekt soll einen Namen, Mitarbeiter (dies wurde wo anders implimentiert), ein inoffizielles Enddatum, eine Beschreibung und einen Farbcode beinhalten, welcher später in der Kalenderansicht sichtbar sein kann. 
Da die Aufgabe ziemlich viel war, da sie sowohl Front-End und Back-End beinhaltete, wurde sie in mehreren Iterationen erstellt. #32



=== Erstellen des Status soll nur noch mit einem gültigen Projektnamen funktionieren

Der Mitarbeiter kann in der Kalenderübersicht sich an für jeden Tag ein bzw. mehrere Projekt(e) anlegen. Dies ging zuvor mit auch mit ungültigen Namen. Dies sollte nicht mehr möglich sein. Die Aufgabe wurde in dieser Iteration abgeschlossen



=== Entscheidung: 
Die Iterationszeit wurde auf 2 Wochen erhöht und daher sollten die Meetings auch bloß aller zwei Wochen stattfinden.
Von dieser Maßnahme wurde sich eine erhöhte Produktivität versprochen. Ob dies gelungen war, wollten wir in maximal zwei Iterationen entscheiden. 

Außerdem wollten wir uns mit Herrn Zirkelbach treffen und ein paar kleine Sachen zu fragen (z.B. zu dem korrigierten Beleg) und unseren Fortschritt mit der Anwendung zu zeigen. Wie bereits in den anderen Iterationen beschrieben, waren Frau Tartz und Herr Keil immer noch Krank und schienen, nach einer Nachfrage bei ihnen, noch länger Krank zu bleiben. 

Herr Keil's Aufgabe wurde nicht mehr vergeben, da wir merkten, dass die Suchfunktion nicht sehr wichtig war und wir die Kräfte mehr bündeln mussten, um an anderen Stellen mit wichtigeren Funktionen Fortschritt zu erzielen. 

== Iteration 13 26.04.22-09.05.22
Unsere Ziele für I13 waren: 
Neubegonnen: Dummy Status einfügen #48 -> fertig
API: Status der Kalenderwoche #49 -> fertig. gab leichte probleme mit in die datenbank einloggen 
API: Erweiterung um das Jahr #50 -> fertig (anscheinend sogar noch am montag -> nicht teil der iteration lul)
API: Einfügen eines neuen Status #52 -> in nächster iteration fertig gestellt 
API: Alle Nutzer eines Projektes #53 -> fertig 
API: REST-API zum Einfügen, Löschen und Abrufen von Nutzern in Projekten #54 -> fertig
Fortgeführt: 
Mehr Dummy-Daten für Project und Project_User #42 -> fertig
Projektverwaltungsseite #45 -> fertig 

=== Implementation

Diese Iteration war davon geprägt, dass viel Arbeit an der API verrichtet wurden ist. Die damit erreichten Funktionen können dann in späteren Implementation in direkte Funktionen umgesetzt werden können.
Es konnten jedoch nicht alle API-Funktionen beendet werden, diese (#52) wurde dann in der nächsten beendet. 
//stimmt das so oder sind die api's bereits eine funktion

Um die Arbeit zu erleichtern wurde Dummy-Stati eingefügt und die Dummy-Projekte aus der letzten Iteration wurden fertiggestellt. (#48 & #42)
Ebenso wurde die Projektverwaltungsseite beendet. #45
//bild


=== Entscheidung
Wir haben uns mit der Produktivität, die wir uns durch die zwei wöchige Iteration erhofft haben, nicht verbessert. Wir gaben diesem Versuch noch eine Iteration, wenn es dann nicht besser wird, gehen wir wie geplant wieder auf sieben Tage pro Iterationzurück.

Herr Keil und Frau Tartz waren immer noch krank, daher sollte her Kemter bei beiden Nachfragen, was Stand der Dinge ist. außerdem war sollte herr kemter, bei frau tartz und herr keil nachfragen, ob diese bald wiederkommen und diese krankheit schonmal herrn anke mitteilen -> was da als antwort kam noch formulieren



I14 10.05.22-16.05.22

Unsere Ziele für I14 waren: 
Neubegonnen:  Status anzeigen #51 -> keine ahnung was da los war
Projekt erstellen in User_Project übernehmen #55 -> bisher noch nicht fertig. was da los? anscheinend, sollte erst einmal ein anderes issue fertig sein und deswegen nicht weiter bearbeitet
Verbleibende Fehler von Psalm beheben #58 -> am letzten tag assigned und dann fertig gestellt
Dummy Daten für Status falsche Wochentage #61 -> fertig
Manuelle Qualitätsprüfung #65 -> fertig, hat keine unerwarten probleme aufgeben, außer fehlermeldung bei "projekt erstellen"
// get_calendar_week.php #62 ohne commit etc geschlossen 

Fortgeführt:
API: Einfügen eines neuen Status #52 -> fertig


entscheidung: da schon lange nicht mehr mit herrn liebert gesprochen, wurde ein meeting geplant, was in der nächsten iteration stattfand

es wurde entschieden (hauptsächlich von niclas), dass wir pull requests verwenden, damit die änderungen das machen was sie machen sollen und man direkt verbesserungen anmerken kann

//ist das eine entscheidung oder eher problem?
wir haben nicht genug skill und zeit unit tests einzuführen. niclas hat daher noch was bei den automatische tests bei den pull requests eingefügt, dass bestimmte fehler erkennen kann 
// war das in der iteration oder davor


I15 17.05.22-23.5.22

Unsere Ziele für I15 waren: 
Neubegonnen: Wechsel der Wochenansicht #66 -> erst bloß vitali und in nächster iteration hat sich vinh noch damit rein gemacht -> fertig
Bug: Falsche Kalenderwoche + Datum wird angezeigt #69 -> komischer bug mit montags und fehler konnte erst nicht behoben werden -> wurde dann aber anscheind behoben

CSS: Projektverwaltung #70 -> wurde von TS gefordert und wurde angefangen und immer weiter geführt
Status hinzufügen #71 -> nicht beendet da schwieriger als erwartet für vinh. wurde aber nicht weitergeführt, da es ein anderes issue erst beendet werden sollte, damit dies zufrieden fertig gestellt wird ????? oder vinh hat einfach das andere fertig gemacht, damit dieses ging
Fortgeführt:


I16 24.05.22-30.05.2022 

Unsere Ziele für I16 waren: 
Projekt erstellen Fehlerbehandlung #68 -> fertig 
Neubegonnen: Datenbankenstruktur: Bei Status den Primary Key ersetzen #63 -> fertig
Fortgeführt: CSS: Projektverwaltung #70 -> vorerst beendet

Entscheidungen: da Jonas keil immer noch nicht da war, haben wir entschieden dies nochmal an herrn anke zu schreiben und ihm mitzuteilen, das wir gegen eine benotung vom ihm sind. herr keil hat sich in der woche zuvor selbstständig abgemeldet

I17 31.05.22-06.06.22 

Unsere Ziele für I17 waren: 
Neubegonnen: Projektverwaltung: Neues Projekt anlegen Erfolgsmeldung #83 -> nicht begonnen und dann von niclas in nächster iteration beendet. muss beendet werden, da von ts im gespräch gefordert
Lizenz für Projekt erarbeiten #84 -> beendet jedoch sind wir uns nicht 100% sicher, dass das so korrekt ist
Benutzerverwaltung: Neuen Benutzer anlegen Erfolgsmeldung #86 -> gleich wie bei #83

Projektverwaltung: Projekte löschen #94 -> agenommen von vinh, aber nicht angefangen. 
Fortgeführt: 

I18

Unsere Ziele für I17 waren: 
Neubegonnen:
Login einfügen #91 -> erst vitali, aber dann niclas fertig gemacht
Fix: Replace is_int with ctype_digit #96 -> fertig
Fortgeführt: Erfolgsmeldung #83 -> von niclas beendet
Benutzerverwaltung: Neuen Benutzer anlegen Erfolgsmeldung #86 -> gleich wie bei #83
Projekte löschen #94 -> erstmal nicht fortgeführt, aber wenn zeit von niclas/vinh 
Wochenansicht: Löschen eines Status #98 -> bloß fertig machen, wenn zeit 
CSS: Design verbessern #102 erst carl zugeteilt, aber wegen treffen macht es doch vinh fertig

Mitarbeiteransicht: Löschen Funktionalität #103 -> gleich wie #98

Testdoku #105; Betriebsdoku #106; Entwicklerdoku #107 -> soll angefangen werden und später fortgeführt 
Projektbericht #116  -> soll angefangen werden und später fortgeführt 

von mittwoch und nicht montag, wegen feiertag


entscheidung: beim 3 mann teammeeting entschieden wir, dass viele geplante programmier issues erstmal keine rolle mehr spielten. grundlegend dafür waren noch 2 wochen bis zur anwenderübergabe -> bloß noch die gewollten änderungen (die bereits davor gemacht werden sollten) und aus unserer sicht die sinnvollsten weitere funktion, wie login und mitarbeiter/projekt löschen
herr kemter wollte herr zirkelbach eh nochmal wegen den projektbericht etwas fragen und hat sich daher noch über weitere aspekte des projekts unterhalten. als folge darauf gab es eine umplanung, der getroffenen entscheidung vom vortag: vitali, justus und carl fingen die test, betriebs, und entwicklerdoku an. vinh übernimmt design anhand der telekomseite und niclas übernimmt die erfolgsmeldungen und login, falls zeit, macht er noch mehr   
all das sollte bis montag geschehen

einige angelegte issues sollten eig vergeben werden, jedoch wurde sich am mittwoch dagegen entschieden diese in dem moment zu vergeben


restliche zeit sollte mit github projekten besser organisiert werden 


kleines krisenmeeting, da noch 2 wochen übrig, aber anwendung noch doku fertig 
entscheidung -> noch wenige elementare features erfüllen und die letzte woche für doku verwenden
    am 9.6. nochmal kurz mit herrn anke/zirkelbach reden


I19
Unsere Ziele für I19 waren: 

//wurden nochmal auf den aktuellen stand gebracht, was/wann abgeben werden muss und die bereits angefangenen doku kommentiert und fragen/probleme beantwortet
Neubegonnen: Anwenderdoku (noch kein issue)
Fortgeführt: Testdoku #105; Betriebsdoku #106; Entwicklerdoku #107 -> da abgeben, soll es eig fertig sein
Projektbericht #116 -> noch nicht fertig, da zu viel aufwand


//entscheidung: es wurde nochmal besprochen, dass alle mit der differentizierten bewertung einverstanden sind
//aleksandra war nicht da, aber entschieden, dass sie noch was machen soll oder wir schreiben nochmal an coach/anke, dass sie eigentlich auch wenig gemacht hat 

I20

I21










Iterationsdauer: 7 Tage. in der mitte des 2. semester mal auf 2 wochen hochgesetzt, da effizienzerhöhung erhofft -> genau das gegenteil -> wieder auf 1 Woche


Wie wurden die Hauptaktivitäten (Analyse, Entwurf, Implementierung, Test, Dokumentation) durchgeführt?
aufgaben wurden kurz nach projekt start als github issue angelegt
analyse und entwurf hauptsächlich im 1. semester
implementierung und test hauptsächlich im 2. semester
dokumentation immer


- Analyse wurde als Gruppe mit TS erfragt
    - die fragen wurden vor dem treffen vorbereitet und danach nochmal nachbereitet
  
- Entwurf wurde dann von 1-2 personen je nach aufgaben erstellt 
    - d.h. welche haben die vision übernernommen, andere die use case diagramme etc
    - die resultate wurden dann im teammeeting besprochen und je nachdem nochmal bearbeitet
    - manchmal hat sich natürlich noch was verändert -> dies wurde dann in späteren 
    iterationen von meist einer person eingepflegt, da es nicht viel war
- implementation
    - wurde hauptsächlich von niclas, justus, vinh, vitali und carl erledigt 
    - niclas hat aufgrund seiner ausbildung (?) schon viel erfahrung gehabt
    - wurde mit docker gearbeitet, damit es egal ist welches OS genutzt wird und es dann wenige probleme bei der übergabe gibt
- test
    - mit psalm und ? wurde php code überprüft
    - durch pull request wurden einige fehler vorm mergen behoben
    - beim programmieren wurde natürlich auch überprüft, ob die veränderungen ungewollte effekte haben
    - es wurden regelmäßig die funktionen in einem "general test" überprüft
    - unit tests sind noch geplant, aber wissen nicht ob dafür zeit ist
- documentation



Welche (wesentlichen) Entscheidungen wurden getroffen? Warum?

- semi offizielle entscheidung, dass aleksandra und nick sich eher um dokumentation kümmern (2. semester)
- nick wird im 2. semester teamleiter, da helena nicht mehr mit macht. die entscheidung war schon etwas im 1. semester geplant, da er daran interesse hatte
- das jonas nicht bewertet werden soll, da er nichts beigetragen hat (passt das hier?)
- niclas sollte sich im 1. semester etwas zurückhalten, da er im 2. beim programmieren gebraucht wird

Was hat gut geklappt, was nicht? Welche Ursachen gab es dafür?

Gut

- im 1. Semester wurden die vergebenen Aufgaben innerhalb von 1 bzw 2 iterationen erfüllt
- jeder hat aufgaben angenommen
- offener meinungsaustausch während der meeting
- erfüllung der aufgaben in guter qualität (-> müssen nicht oft nacharbeiten bzw bloß kleinigkeiten)

- bloß weil hier nicht mehr/alles genannt wird, heißt es nicht, dass nichts mehr gut war 
-> sondern bloß schwierig das alles zu benennen

Schlecht

- im 2. semester wurden öfter die gleichen aufgaben über mehrere iterationen gezogen und commit waren z.T. erst kurz vor teammeeting gepushed. das hat vermutlich den grund, dass wir ziemlich gut im 1. semester mit relativ wenig aufwand waren und dachten, dass geht so weiter bzw. einfach faulheit
- bei coding fragen, wurde niclas nicht gefragt und daher die probleme auf "die lange bank geschoben"
- zu wenig, die wirklich gut coden konnten
- kranke teammitglieder (können daran nichts ändern)
- manche teammitglieder haben öfters bei teammeeting gefehlt (aus verschiedenen gründe. krankheit oder andere termine)
//sollen die mitglieder namentlich genannt werden?

Wie wurde mit Problemen umgegangen? Haben die getroffenen Maßnahmen gewirkt?

- iterationszeit erhöht, damit mehr gemacht wird -> nein, eher das gegenteil
- Nick hat HTML/CSS gelernt und konnte dann etwas vom verbesserten Design erstellen 
- niclas hat immer gesagt, dass man ihn eher fragen soll -> aber die anderen haben sich 
nicht getraut / haben die aufgaben zu spät angefanen um zu fragen(?)