//die zeitformen sind ziemlich "unpräzise" und wechseln oft (keine ahnung welche man verwenden muss)
//Problem: aufgaben wurden erstellt und vergeben dann wurden die zwar angefangen zu bearbeiten aber nicht beendet
//darauf achten das immer benutzer anstatt mitarbeiter genutzt wurde (wurde ziemlich oft nicht beachtet)
//weiterhin haben wir/ich bei den programmieraufgaben im Iterationsplan oft "weitere funktionen" geschrieben, aber nicht was genau getan wurde
//das kann zwar mithilfe der issues etwas nachverfolgt werden, aber auch nicht perfekt, da die manchmal erstellt aber nicht assignet wurden 

= Projektdurchführung

== Problem:
Zu Beginn des neuen Semesters wurde relativ schnell deutlich, dass die Arbeitsmoral der einzelnen Teammitglieder weit auseinander gehen sollte. Das wurde besonders durch die Zeitplanungstabelle deutlich. Leider beeinflusste dies auch die Moral der bisher noch motivierten Teammitglieder. 
Daher lag die Entscheidung nahe, das Angebot des Prof Anke zu nutzen und ein neues Teammitglied anzuwerben. Der Effekt auf Arbeitsmoral und Fortschritt war unverkennbar. Dennoch gelang es nicht alle Anforderungen an die Software zu realisieren.

== I09

Iteration 9 (23.03.22 - 28.03.22) war die erste Iteration im neuen Semester. Wir hatten wegen der Semesterferien fast 2 Monate nicht mehr an dem Projekt gearbeitet. Daher mussten wir uns erst einmal wieder einen Überblick über den aktuellen Stand verschaffen und unsere Fähigkeiten aus dem Winterschlaf holen. 
//passt der joke oder soll das raus?
Frau Rubein hat das Projekt verlassen, da Sie Software Engineering II nicht mehr belegt.

Nicht passend dafür war der krankheitsbedingte Ausfall von Herrn Keil und Frau Tartz, diese sollen noch weitere Wochen ausfallen. 
//risiko 

Unsere Ziele für I09 waren: 
Neubegonnen:

-Nutzerübersichtsseite #39

-Datenbanktabelle für Beziehung zwischen Projekt und Benutzer #38

-Mitarbeiter anlegen um Abteilungsdropdown erweitern #35 

//wurde erst später beendet, aber naja
-Aufräumen der Datenbankenstruktur #37

-Anlegen der Abteilungstabelle + 5 Abteilungen #34

-Mitarbeiter hinzufügen check der E-Mail #33

-Mitarbeiter hinzufügen Passwortkriterien #36

//später nochmal geöffnet
//-Praktikumsfragen #31  
//da war doch ein coach treffen oder? ja am 22.4
-Beleg korrigieren #29

//andere Reihenfolge und ohne #
//überschriften?


=== Dokumentation

Wie bereits geschrieben, hat Herr Anke unseren abgegeben Beleg über die Semesterferien korrigiert. Auch wenn es nicht viele Fehler gab, mussten diese natürlich korrigiert werden. 
Manche Fehler waren schlechter Ausdruck oder es es fehlten Kleinigkeiten bei sonst korrektem Inhalt. Dies konnte schnell behoben werden. 

Die schwerwiegerenden Fehler waren die komplett falsche "logische Sicht". Dort wurde mit einem C4-Modell gerechnet, welches wir jedoch nicht hatten. Daher musste dieses von Grund auf erstellt werden. Da das Back-End zu dem Zeitpunkt noch nicht komplett fertig war, wurden erst einmal die beiden oberen Sichten angefertigt. Eventuelle weitere Sichten sollten möglicherweise im weiterem Verlauf des Projekts folgen. 
//nennt man das Sichten?
Außerdem fehlte der komplette Abschnitt "Praktiken und Bewertung". Diese Aufgabe war nicht unbedingt schwierig, jedoch war es viel daher konnte die Bearbeitung nicht in dieser Iteration beendet werden.


=== Implementation


Die Datenbank musste aktualisiert werden, damit weitere Funktionen realisiert werden können.
Die beiden Aufgaben konnten ohne Probleme beendet werden. (#34 und #38)


UC3

Herr Liebert wollte eine Übersicht über einen Benutzer haben, wenn dieser in der Kalenderübersicht angeklickt wird. Dort sollte Name, Abteilung und Lösch- sowie Bearbeitungsmöglichkeiten des Mitarbeiters angezeigt werden. Da wir keine Button ohne direkt geplante Funktion haben wollte, wurde der Lösch- und Bearbeitungsbutton nicht umgesetzt und war daher für später geplant. (#39)
//bild einfügen

Natürlich soll wenn ein neuer Mitarbeiter angelegt wird, eine Email erstellt werden, welche zumindest den formalen Anforderungen an eine Email entspricht. Dies wurde erledigt. (#33)

//das wurde beendet oder?
Ebenso soll das verwendete Passwort minimalen Sicherheitsstandards entsprechen.

Da die RegEx - Regeln nicht nur Frontend-seitig überprüft werden sollten und der zugehörige Backend PHP-Code nicht besonders einfach ist, konnte dieses Issue erst später beendet werden. Dieses Issue hatte außerdem nicht die höchste Priorität. #36

Bei der Erstellung soll die Abteilung des Mitarbeiters aus einem Dropdown-Menü auswählbar sein. Dies stellte kein Problem dar. 

=== Problem

Zu diesem Zeitpunkt fehlten Herr Keil und Frau Tartz bei dem wöchentlichen Teammeeting. Wir entschieden uns noch keine "Maßnahmen" zu treffen, da dies auch einfach eine normale Krankheit bzw. anderweitige terminliche Schwierigkeit sein konnte.

=== Entscheidungen:

Herr Kemter hat sich bereit erklärt als Teamleiter zu fungieren, da Frau Rubein diese Rolle zuvor Inne hatte.


== Iteration 10  

29.03.22 - 04.04.22
//wo sind hier die aufgaben, als ob nichts neues begonnen wurden ist

//niklas hat bei problemen geholfen -> deswegen wenig
Unsere Ziele für I10 waren: 

Neubegonnen:

Suche implementieren #28 -> nie von jonas keil angefangen und auch nicht wichtig genug, das es weitergeführt wird, da kräfte gesammelt werden mussten

Mehr Dummy-Daten für Project und Project_User #42 -> assigned aber nie begonnen erst am 25.4

Fortgeführt: 

Beleg korrigieren #29

Mitarbeiter hinzufügen Passwortkriterien #36

=== Dokumentation

Risikoliste erweitert. Dokumente aktuell gehalten (auch wenn es evtl. nichts neues gab??)

=== Implementation

Es sollte eine simple Suchfunktion eingefügt werden, sodass nach Mitarbeiter und Projekten gesucht werden kann und bloß diese Angezeigt werden. Diese Aufgabe wurde Herr Keil in Abwesenheit gegeben.

//das hat kein direkten use case
UC 03

Es sollten Dummy-Daten für Projekte eingefügt, damit damit gleich die Funktionaltität überprüft werden konnte und das spätere Arbeiten angenehmer gestaltete. Jedoch wurde dies nie begonnen und daher in der nächsten Iteration fortgeführt.

Leider konnten die Passwortkriterien-Aufgabe immer noch nicht abgeschlossen werden. 


== Problem

Es wurden kaum neue Aufgaben vergeben, zeitgleich gab es aber auch kaum alte zum fortführen. Hier wurde das 1. Mal gemerkt, dass das Projekt zu stocken beginnt. Jedoch hatten wir die Hoffnung, dass dies in der nächsten Iteration besser wird.
//was hatte das für einen Grund und wieso war das in der nächsten woche noch einmal 

== Iteraion 11 05.04.22. - 11.04.22

Unsere Ziele für I11 waren: 
//wo sind hier die aufgaben, als ob nichts neues begonnen/fortgeführt wurden ist
Neubegonnen:  -Erstellen des Status soll nur noch mit einem gültigen Projektnamen funktionieren #30

Projekterstellungsseite Frontend+Backend #32

Fortgeführt:

Beleg korrigieren #29

Mitarbeiter hinzufügen Passwortkriterien #36

Mehr Dummy-Daten für Project und Project_User #42

=== Dokumentation

Die restlichen Fehler bzw. Ungenauigkeiten des Belegs konnten behoben werden. Dazu zählten Praktiken und Bewertung, sowie das C4-Model.

=== Implementaton

UC 03

Wenn ein Projekt angelegt wird, sollte dies bloß noch mit einem eingetragenen Namen möglich sein. 

Dieses Mal konnten die Dummy-Daten eingefügt werden.

=== Problem 

Es zeichnete sich ab, dass neben dem Fernbleiben von Herrn Keil und Frau Tartz auch einige andere Teammitglieder eine nur geringe Beteiligung vorweisen konnten. Dieser Umstand wurde im Teammeeting thematisiert und um Besserung gebeten, aber aufgrund fehlender Dringlichkeit wurde von weiteren Maßnahmen abgesehen. 

== Iteration 12 12.04.22-25.04.22

In dieser Iteration wurden endlich wieder neue Aufgaben begonnen und wir bekammen ein neues Mitglied, welches im Front-End und Back-End gut bewandert war. Dies war eine nötige Verstärkung für uns, da wir sonst gefahr liefen, dass wir aufgrund von "nicht Wissen" nicht weiter bzw. langsam vorankommen (risiko)
moral ++

Unsere Ziele für I12 waren: 

Neubegonnen: 

    Beleg aktuell halten bzw. weiterbearbeiten #41  -> dauerauftrag

    Projekterstellungsseite Frontend+Backend #32

    Mehr Dummy-Daten für Project und Project_User #42 -> nicht geschafft und dann neu vergeben an Carl

    API: Aktuelle Kalenderwoche #43 -> fertig

    Projektverwaltungsseite #45 -> angefangen aber nicht fertig, daher später weitergemacht      

    Neues Mitglied Vinh einführen

Fortgeführt:

Projekterstellungsseite Frontend+Backend #32

=== Dokumentation

Da der Beleg aktuell war, musste bloß unser neues Mitglied Vinh Nguyen in die Dokumentation eingetragen und darin geschult werden, damit er damit umgehen kann.

Risikoliste erweitert

=== Implementation
//sicher das ich die UC nicht zt vertauscht habe, da ich mir die falsch gemerkt habe
UC 01

Die API Funktion wurde so erweitert, dass sie nun die aktuelle Kalenderwoche mit Daten anzeigen kann. #43

UC 04

Elementarer Bestandteil des SEII-Projekts war es, dass Projekte angelegt werden können. Das Projekt soll einen Namen, Mitarbeiter (dies wurde wo anders implimentiert), ein inoffizielles Enddatum, eine Beschreibung und einen Farbcode beinhalten, welcher später in der Kalenderansicht sichtbar sein kann. Da die Aufgabe ziemlich viel war, da sie sowohl Front-End und Back-End beinhaltete, wurde sie in mehreren Iterationen erstellt. #32

Zu diesem Use-Case zählt ebenfalls, dass Mitarbeiter einem Projekt zugewiesen und entzogen werden kann. Dies wurde ebenfalls angefangen, jedoch nicht beendet. #45

=== Entscheidung: 

Um die Produktivität zu erhöhen wurd die Iterationszeit auf 2 Wochen erhöht. Daher sollten die Meetings ebenfalls aller zwei Wochen stattfinden.

Ob dies die gewünschte Veränderung mit sich brachte, sollte innerhalb von zwei Iterationen überprüft werden.


//den absatz in problem und dann entscheidung auseinandernehmen

Außerdem wollten wir uns mit Herrn Zirkelbach treffen und ein paar Kleinigkeiten zu erfragen (z.B. zu dem korrigierten Beleg) und unseren Fortschritt mit der Anwendung zu zeigen. 

=== Problem 

Die bisher teilweise bemängelte Produktivität verbesserte sich im Gesamtbild spürbar, auch wenn das nicht auf jedes einzelne Teammitglied zurückgeführt werden konnte.

Wie bereits in den anderen Iterationen beschrieben, waren Frau Tartz und Herr Keil immer noch Krank und schienen, nach einer Nachfrage bei ihnen, noch länger Krank zu bleiben. 

Herr Keil's Aufgabe wurde nicht mehr vergeben, da wir merkten, dass die Suchfunktion nicht sehr wichtig war und wir die Kräfte mehr bündeln mussten, um an anderen Stellen mit wichtigeren Funktionen Fortschritt zu erzielen. 

== Iteration 13 26.04.22-09.05.22

Unsere Ziele für I13 waren: 

Neubegonnen: Dummy Status einfügen #48 -> fertig

API: Status der Kalenderwoche #49 -> fertig. gab leichte probleme mit in die datenbank einloggen 

API: Erweiterung um das Jahr #50 -> fertig (anscheinend sogar noch am montag -> nicht teil der iteration lul)

API: Einfügen eines neuen Status #52 -> in nächster iteration fertig gestellt 

API: Alle Nutzer eines Projektes #53 -> fertig 

API: REST-API zum Einfügen, Löschen und Abrufen von Nutzern in Projekten #54 -> fertig

Fortgeführt: 

Mehr Dummy-Daten für Project und Project_User #42 -> fertig

Projektverwaltungsseite #45 -> fertig 

=== Dokumentation 

Die Risikoliste wurde erneut im einen Eintrag erweitert. Herr Nguyen hatte ein neues Tool verwendet, was ihm eigentlich Arbeit abnehmen sollte. Jedoch hatte dieses einen ungewollten Effekt, welcher am Ende mehr Arbeit war, da das bearbeitete Dokument manuell wieder auf seinen Ursprünglichen Zustand gebracht werden musste. 


=== Implementation

UC 01

Diese Iteration war davon geprägt, dass viel Arbeit an der API verrichtet worden ist. Die damit erreichten Funktionen können dann in späteren Implementation in direkte Funktionen umgesetzt werden können. #52 # 53 #49???
// schaue später nach
Es konnten jedoch nicht alle API-Funktionen beendet werden. (#52)  
//stimmt das so oder sind die api's bereits eine funktion?

Um die Arbeit zu erleichtern wurde Dummy-Status eingefügt und die Dummy-Projekte aus der letzten Iteration wurden fertiggestellt. (#48 & #42)

//bild --> wie loggt man sich jetzt an? ^^

UC 04

Die Arbeiten am UC04 aus der vorherigen Iteration konnten abgeschlossen werden. #42 #45

=== Entscheidung

Bisher ist eine Verbesserung hinsichtlich der Produktivität nicht erkennbar. 

Herr Keil und Frau Tartz haben sich nach wie vor nicht an dem Projekt beteiligt und das Team auch weiterhin nicht über den aktuellen Stand selbstständig in Kenntnis gesetzt. Daher war es Herr Kemters Aufgabe diese Informationen einzuholen.

Frau Tartz teilte mit, dass sie auf dem Weg der Besserung sei und sich in Zukunft wieder an dem Projekt beteiligen werde.

Leider war festzustellen, dass Herr Keil weiterhin gesundheitlich bedingt verhindert war. Daher musste das Team auf ihn weiterhin verzichten. Des weiteren wurde Herr Professor Anke über diese Situation in Kenntnis gesetzt.

Aufgrund beschrieben Softwarevorfalls in dieser Iteration bei Herrn Nguyen wurde beschlossen, dass die neu genutzten Tools auf ein Minimum zu beschränken sind. Falls neue Tools notwendig sind, soll sich der Nutzer über diese davor informieren. 


=== I14 10.05.22-16.05.22

Unsere Ziele für I14 waren: 
Neubegonnen:  Status anzeigen #51 -> keine ahnung was da los war

Verbleibende Fehler von Psalm beheben #58 -> am letzten Tag assigned und dann fertig gestellt

Dummy Daten für Status falsche Wochentage #61 -> fertig

Manuelle Qualitätsprüfung #65 -> fertig, hat keine unerwarten Probleme aufgeben, außer Fehlermeldung bei "Projekt erstellen"
// get_calendar_week.php #62 ohne commit etc geschlossen 

Fortgeführt:

API: Einfügen eines neuen Status #52 -> fertig


=== Entscheidung

Wir hatten schon länger kein Meeting mit unserem Themensteller Herrn Liebert. Dies hatte den Grund, dass wir die geforderten Use-Cases noch nicht umgesetzt hatten und es daher keinen Grund gab ihn zu treffen. Ein Monat vor Projektübergabe und mit voranschreitenden Funktionen entschieden wir uns ein Meeting mit ihm auszumachen. Außerdem sollte besprochen werden, wie die Übergabe und das Installieren der Anwendung bei T-System MMS stattfinden soll. Das Meeting fand in der folgenden Woche statt.

Wir führten Pull-Requests ein. Dies vereinfachte die Qualitätssicherung und die Kommunikation über mögliche Verbesserung erstellter Commits.

Die Erhöhung der Iterationszeit auf zwei Wochen führte nicht zu der erwünschten Verbesserung, sondern zu einer weiteren Verschlechterung der Produktivität. Daher wurde entschieden, die folgenden Interationen wieder auf eine Woche zu verkürzen.

Da immer weniger an der Dokumentation zu erledigen war, wurde Herr Kemter in HTML und CSS fortgebildet, um bei späteren Aufgaben zu helfen.

//ist das eine entscheidung oder eher problem?
=== Problem

Wir hatten bisher weder die Erfahrung noch die Zeit Unit-Tests durchzuführen. 
// wir hatten schon zu dem Zeitpunkt schon ein Praktikum zu Unit-Tests 
Wir hatten bis jetzt nur eine kleine Einführung im Praktikum zu Unit-Tests, da aber die Zeit uns davon rannte und wir noch weitere große Aufgaben 
Daher wurde Frau Tartz damit beauftragt manuelle Tests durchzuführen. Außerdem wurden statische Codeanalysen für PHP und JavaScript eingeführt. Diese analysieren den Code auf unbenutzte Variabeln und Codestücke sowie auf unsichere Funktionen.
//stimmt das so?
//war das in der iteration oder davor?? da #58 dies vermuten lässt
//und das sollte glaube nochmal positiver/anders formuliert werden


== Iteration 15 
17.05.22-23.5.22

Unsere Ziele für I15 waren: 
//gefühlt hat bloß vinh hier was erledigt
Neubegonnen: Wechsel der Wochenansicht #66 -> erst bloß vitali und in nächster iteration hat sich vinh noch damit rein gemacht -> fertig
Bug: Falsche Kalenderwoche + Datum wird angezeigt #69 -> komischer bug mit montags und fehler konnte erst nicht behoben werden -> wurde dann aber anscheind behoben

CSS: Projektverwaltung #70 -> wurde von TS gefordert und wurde angefangen und immer weiter geführt
Status hinzufügen #71 -> nicht beendet da schwieriger als erwartet für vinh. wurde aber nicht weitergeführt, da es ein anderes issue erst beendet werden sollte, damit dies zufrieden fertig gestellt wird ????? oder vinh hat einfach das andere fertig gemacht, damit dieses ging
Fortgeführt:

=== Feedback vom Themensteller

Herr Liebert war generell zufrieden mit unserem Fortschritt. 
Er forderte, dass nach der Erstellung eines Mitarbeiters oder eines Projektes eine Bestätigung der Aktivität angezeigt werden und die Seite wieder zurück auf die Kalenderansicht wechseln soll. Außerdem merkte er an, dass das Design noch verbessert werden sollte. Diese Anmerkungen setzten wir als Issues für die kommenden Iterationen an.
Die Übergabe wurde auf den 22.06.2022 festgelegt. 
Herr Liebert möchte nicht, dass wir die Anwendung vor der Übergabe auf den Systemen von T-System MMS testen, da er davon überzeugt ist, dass aufgrund der Nutzung von Docker es keine Probleme geben wird. Wir teilen diese Meinung nur bedingt und wären lieber besser auf alle Eventualitäten vorbereitet. Wir werden versuchen ihn zu einem späteren noch einmal darauf anzusprechen und dies auch schriftlich festhalten. 


=== Implementation

//sind das nicht quasi alle use cases?
Die geforderten Designverbesserungen wurden von Herrn Kemter begonnen und über die nächsten Iterationen fortgeführt. Das Ziel war eine bessere Darstellung der Inhalte. Zuvor wurden diese z.T. hochkant dargestellt. Außerdem sollte die Lesbarkeit verbessert und dem Benutzer ein verbessertes Feedback gegeben werden, was anklickbar ist.


UC 01

Für den Use-Cas 01 fehlte noch ein elementares Feature. Was ist eine Kalenderanwendung, wenn es nicht möglich ist, dass die Wochen gewechselt werden können? Daher sollte dies realisiert werden. Leider wurde es diese Iteration nicht beendet.
//fehlt noch mehr


== Iteration 16 
24.05.22-30.05.2022 

Unsere Ziele für I16 waren: 
Projekt erstellen Fehlerbehandlung #68 -> fertig 
Neubegonnen: Datenbankenstruktur: Bei Status den Primary Key ersetzen #63 -> fertig
Fortgeführt: CSS: Projektverwaltung #70 -> vorerst beendet
Wechsel der Wochenansicht #66

=== Entscheidung
Herr Keil war immernoch unabkömmlich. Daher haben wir entschieden diesen Sachverhalt nochmal Herrn Professor Anke darzulegen und ihm mitzuteilen, dass wir gegen eine Benotung von Herrn Keil sind. Wir begründeten diese Entscheidung damit, dass er keine Chance mehr hatte einen angemessenen Arbeitsanteil zu leisten. Von Herrn Professor Anke erfuhren wir, dass sich Herr Keil bereits in der Woche zuvor selbstständig abgemeldet hatte.

Hinsichtlich der weiterhin unterschiedlichen Beteiligung einiger Teammitglieder, wurde sich für eine differenzierte Bewertung ausgesprochen. Wie extrem unsere Empfehlungen dafür ausfallen werden, sollte daran bemessen werden wie diese Teammitglieder in den restlichen Wochen sich am Projekt beteiligen werden.
//war das hier auch mit der differenzierten bewertung besprochen wurden?

== Iteration 17 
31.05.22-06.06.22 

Unsere Ziele für I17 waren: 
Neubegonnen: Projektverwaltung: Neues Projekt anlegen Erfolgsmeldung #83 -> nicht begonnen und dann von niclas in nächster iteration beendet. muss beendet werden, da von ts im gespräch gefordert
Lizenz für Projekt erarbeiten #84 -> beendet jedoch sind wir uns nicht 100% sicher, dass das so korrekt ist
Benutzerverwaltung: Neuen Benutzer anlegen Erfolgsmeldung #86 -> gleich wie bei #83

Projektverwaltung: Projekte löschen #94 -> agenommen von vinh, aber nicht angefangen. 
Fortgeführt: 

== Iteration 18
09.06.2022-13.06.2022

Aufgrund der Feiertage fand unser Teammeeting und Iteration von Mittwoch bis Montag statt. 

Unsere Ziele für I17 waren: 
Neubegonnen:
Login einfügen #91 -> erst vitali, aber dann niclas fertig gemacht
Fix: Replace is_int with ctype_digit #96 -> fertig
Projektbericht
Fortgeführt: Erfolgsmeldung #83 -> von niclas beendet
Benutzerverwaltung: Neuen Benutzer anlegen Erfolgsmeldung #86 -> gleich wie bei #83
Projekte löschen #94 -> erstmal nicht fortgeführt, aber wenn zeit von niclas/vinh 
Wochenansicht: Löschen eines Status #98 -> bloß fertig machen, wenn zeit 
CSS: Design verbessern #102 erst carl zugeteilt, aber wegen treffen macht es doch vinh fertig

Mitarbeiteransicht: Löschen Funktionalität #103 -> gleich wie #98

Testdoku #105; Betriebsdoku #106; Entwicklerdoku #107 -> soll angefangen werden und später fortgeführt 
Projektbericht #116  -> soll angefangen werden und später fortgeführt -> als doku wird auch die UC nochmal angeschaut und aktualisiert

von mittwoch und nicht montag, wegen feiertag

doku: riskliste mit lust

=== Problem und Entscheidung

Das Teammeeting fand aufgrund von kurzfristigen Absagen bloß mit drei Personen statt. Aufgrund der Anwenderabgabe und Dokumentation in zwei Wochen entschieden wir, dass Programmierissues bloß noch bis zum folgenden Montag erledigt werden. Die restliche Zeit bis zur Abgabe sollte dann für Dokumentation und andere Dokumente verwendet werden. 
Da noch nicht alle kleinen aber doch wichtigen Features, die durch Herrn Liebert gefordert wurden, zum Meeting abgeschlossen waren, sollten diese erledigt werden. Wenn mehr geschafft wird, dann kann noch mehr erledigt werden.

Herr Kemter hat sich wegen des Projektberichts nochmal mit Herrn Zirkelbach unterhalten. Dabei kam auch unsere Entscheidung zu sprechen und das zumindest einige Teammitglieder mit dem Endergebnis und der Arbeitsweise unzufrieden sind.
Herr Zirkelbach empfiehl Herr Kemter, dass die Programmieraufgaben bloß noch von Herrn Werner und Herrn Nguyen erfüllt werden und die anderen Personen bloß Dokumentieren sollen. Diese Empfehlung folgten wir.


Auch wenn Herr Kemter das Design und Aufbau der einzelnen Seiten verbessert hatte, waren wir noch nicht zufrieden. Daher hat Herr Nguyen diese nochmal verbessert und sich dabei an den Seiten von T-System MMS orientiert, damit sich unsere Anwendung dieser ähnelt. 

Die restlichen Iterationen sollten nun nochmal besser mit GitHub Projekten verwaltet werden.

=== Dokumentation

Herr Kemter begann den "Durchführungs"-Teil des Projektberichtes. Hier gab es die "Schwierigkeit", welchen genauen Aufbau es geben soll. Hier stellten die von Herrn Professor bereitgestellen Beispiele eine gute Grundlage. Schließendlich entschied er sich für eine Nennung der neu angefangenen und fortgeführten Issues. Ob dies noch einmal geändert wird steht noch offen. Weiterhin wird er in einzelnen Abschnitten die Implementation, Entscheidungen, Probleme und eventuelle weitere Themen beschreiben.

//herr kemter wollte herr zirkelbach eh nochmal wegen den projektbericht etwas fragen und hat sich daher noch über weitere aspekte des projekts unterhalten. als folge darauf gab es eine umplanung, der getroffenen entscheidung vom vortag: vitali, justus und carl fingen die test, betriebs, und entwicklerdoku an. vinh übernimmt design anhand der telekomseite und niclas übernimmt die erfolgsmeldungen und login, falls zeit, macht er noch mehr   
//all das sollte bis montag geschehen

//einige angelegte issues sollten eig vergeben werden, jedoch wurde sich am mittwoch dagegen entschieden diese in dem moment zu vergeben


//restliche zeit sollte mit github projekten besser organisiert werden 


//kleines krisenmeeting, da noch 2 wochen übrig, aber anwendung noch doku fertig 
//entscheidung -> noch wenige elementare features erfüllen und die letzte woche für doku verwenden
//    am 9.6. nochmal kurz mit herrn anke/zirkelbach reden


=== Iteration 19 
14.6.2022 - 20.06.2022
Unsere Ziele für I19 waren: 

//wurden nochmal auf den aktuellen stand gebracht, was/wann abgeben werden muss und die bereits angefangenen doku kommentiert und fragen/probleme beantwortet
Neubegonnen: Anwenderdoku (noch kein issue)
programmier zeugs
Fortgeführt: Testdoku #105; Betriebsdoku #106; Entwicklerdoku #107 -> da abgeben, soll es eig fertig sein
Projektbericht #116 -> noch nicht fertig, da zu viel aufwand

=== Dokumentation 

Durch die Entscheidung aus der vorherigen Iteration wurde diese Iteration viel an den Dokumenten gearbeitet. Diese umfassten das Besichtigen und verbessern der Test-, Betriebs- und Entwicklerdokumentation. Hier wurden gute Grundlagen gelegt, jedoch reichte es noch für die Abgabe aus. Daher wurden sie weiterverbessert. Die Anwenderdoku sollte auch erledigt werden, jedoch wussten wir nicht, ob eventuell noch kleine Verbesserungen realsiiert werden, was Teile der Anwenderdokumentation sinnlos erscheint lässt.
//komischer satz
Wie auch in den Wochen davor wurde sich auf den Projektbericht fokusiert. Diesen hat Herr Kemter den Inhalt erweitert und dann mit Herrn Beck auf Verständlichkeit und Inhalt korrigiert. 

Außerdem wurde noch einmal die Differenzierte Bewertung angesprochen, da sich einige Mitglieder weiterhin nicht in angemessenen Maße beteiligt haben.
//entscheidung: es wurde nochmal besprochen, dass alle mit der differentizierten bewertung einverstanden sind
//aleksandra war nicht da, aber entschieden, dass sie noch was machen soll oder wir schreiben nochmal an coach/anke, dass sie eigentlich auch wenig gemacht hat 

== Iteration 20

vortrag


== Iteration 21










Iterationsdauer: 7 Tage. in der mitte des 2. semester mal auf 2 wochen hochgesetzt, da effizienzerhöhung erhofft -> genau das gegenteil -> wieder auf 1 Woche


Wie wurden die Hauptaktivitäten (Analyse, Entwurf, Implementierung, Test, Dokumentation) durchgeführt?
aufgaben wurden kurz nach projekt start als github issue angelegt
analyse und entwurf hauptsächlich im 1. semester
implementierung und test hauptsächlich im 2. semester
dokumentation immer


- Analyse wurde als Gruppe mit TS erfragt
    - die fragen wurden vor dem treffen vorbereitet und danach nochmal nachbereitet
  
- Entwurf wurde dann von 1-2 personen je nach aufgaben erstellt 
    - d.h. welche haben die vision übernernommen, andere die use case diagramme etc
    - die resultate wurden dann im teammeeting besprochen und je nachdem nochmal bearbeitet
    - manchmal hat sich natürlich noch was verändert -> dies wurde dann in späteren 
    iterationen von meist einer person eingepflegt, da es nicht viel war
- implementation
    - wurde hauptsächlich von niclas, justus, vinh, vitali und carl erledigt 
    - niclas hat aufgrund seiner ausbildung (?) schon viel erfahrung gehabt
    - wurde mit docker gearbeitet, damit es egal ist welches OS genutzt wird und es dann wenige probleme bei der übergabe gibt
- test
    - mit psalm und ? wurde php code überprüft
    - durch pull request wurden einige fehler vorm mergen behoben
    - beim programmieren wurde natürlich auch überprüft, ob die veränderungen ungewollte effekte haben
    - es wurden regelmäßig die funktionen in einem "general test" überprüft
    - unit tests sind noch geplant, aber wissen nicht ob dafür zeit ist
- documentation



Welche (wesentlichen) Entscheidungen wurden getroffen? Warum?

- semi offizielle entscheidung, dass aleksandra und nick sich eher um dokumentation kümmern (2. semester)
- nick wird im 2. semester teamleiter, da helena nicht mehr mit macht. die entscheidung war schon etwas im 1. semester geplant, da er daran interesse hatte
- das jonas nicht bewertet werden soll, da er nichts beigetragen hat (passt das hier?)
- niclas sollte sich im 1. semester etwas zurückhalten, da er im 2. beim programmieren gebraucht wird

Was hat gut geklappt, was nicht? Welche Ursachen gab es dafür?

Gut

- im 1. Semester wurden die vergebenen Aufgaben innerhalb von 1 bzw 2 iterationen erfüllt
- jeder hat aufgaben angenommen
- offener meinungsaustausch während der meeting
- erfüllung der aufgaben in guter qualität (-> müssen nicht oft nacharbeiten bzw bloß kleinigkeiten)

- bloß weil hier nicht mehr/alles genannt wird, heißt es nicht, dass nichts mehr gut war 
-> sondern bloß schwierig das alles zu benennen

Schlecht

- im 2. semester wurden öfter die gleichen aufgaben über mehrere iterationen gezogen und commit waren z.T. erst kurz vor teammeeting gepushed. das hat vermutlich den grund, dass wir ziemlich gut im 1. semester mit relativ wenig aufwand waren und dachten, dass geht so weiter bzw. einfach faulheit
- bei coding fragen, wurde niclas nicht gefragt und daher die probleme auf "die lange bank geschoben"
- zu wenig, die wirklich gut coden konnten
- kranke teammitglieder (können daran nichts ändern)
- manche teammitglieder haben öfters bei teammeeting gefehlt (aus verschiedenen gründe. krankheit oder andere termine)
//sollen die mitglieder namentlich genannt werden?

Wie wurde mit Problemen umgegangen? Haben die getroffenen Maßnahmen gewirkt?

- iterationszeit erhöht, damit mehr gemacht wird -> nein, eher das gegenteil
- Nick hat HTML/CSS gelernt und konnte dann etwas vom verbesserten Design erstellen 
- niclas hat immer gesagt, dass man ihn eher fragen soll -> aber die anderen haben sich nicht getraut / haben die aufgaben zu spät angefanen um zu fragen(?)