//verwende glaube immer unterschiedliche und falsche zeitformen

= Planung

== Ausgangssituation in Software Engineering II

===  Auftraggeber und Aufgabenstellung

Im Rahmen des Moduls "Software Engineering II" haben wir die Aufgabe erhalten eine Art Kalender für T-Systems MMS zu entwickeln. Unser Ansprechpartner in der Firma war Herr Sven Liebert und in der HTW Dresden waren es Herr Zirkelbach als Coach und Herr Prof. Anke als Dozent.

Die Webanwendung solle den Mitarbeitenden ermöglichen ihre geplanten Projekte in einen Kalenderübersicht einzutragen. Die Darstellung soll ohne konkrete Zeit auskommen und soll Darstellen an was der Mitarbeitende an diesen Tag gearbeitet hat bzw. plant zu arbeiten. Dafür sollen Projekte und Mitarbeitern erstellt werden können. Die Mitarbeiter sollen ebenfalls zu Abteilungen zugeordnet werden können. Jeder Mitarbeiter hat soll Projekte und andere Mitarbeiter erstellen bzw. bearbeiten können. Ebenso darf jeder Mitarbeiter, auch für Kollegen, die Projekte für die jeweiligen Tage ein- bzw- austragen können
Feiertage und Betriebsferien sollen über ebenfalls dargestellt werden. Für die Feiertage soll eine spezielle API verwendet werden. Für die Betriebsferien bzw. Bundesland abhängige Feiertage sollen diese Tage "per Hand" erstellt werden können.


//immer "soll" -> synonyme 
//API nennen?
===  Situation zum Semesterbeginn

Unser Team hat bereits letztes Semester an diesem Projekt gearbeitet. Daher haben wir dank guter Vorarbeit eine Dokumentation, welche bereits auf einem guten Stand war und bloß kleine Verbesserungen benötigte. 
Die Anwendung selbst war auch auch begonnen. Große Teile des Front-Ends waren auch schon funktional erstellt. Es fehlte z.B.  noch die Seite für die Projekterstellung, jedoch ist dies im Front-End eine reine Formsache. Wenige Grundlegende Back-End-Strukturen und -funktionen waren auch schon angelegt, wie z.B. die Datenbank und das anzeigen von Mitarbeitern.

//passt das mit der Fortschrittbeschreibung der Anwendung?
//fähigkeiten der mitglieder


===  Team und Rollen

Unsere Rollen bzw. Verantwortlichkeiten wurden soweit möglich nach bereits vorhandener Kompetenz vergeben. Dies trifft auf Herrn Werner, Herrn Beck, Herrn Tichonow und später auch auf Herrn Nguyen zu. Frau Rubein, Frau Tartz, Herr Kemter, Herrn Keil und Herr Kirchhoff mussten sich ihre Kompetenz erst erarbeiten und haben daher Rollen erhalten, welche mit ihren bisherigen Stärken und Interessen die größte Schnittmenge haben. 

Aus den ursprünglichen acht Mitgliedern wurden im 2. Teil des Projekts bloß zwischenzeitlich noch 7, da Frau Rubein Wirtschaftsingeneurin ist und damit Software Engineering II nicht mehr belegt. Jedoch bekam unser Team nach wenigen Wochen Herr Nguyen als Nachzügler in unser Team. Dieser hatte bereits Programmiererfahungen und bekam daher die Verantwortung der Implementation erhalten. Herr Keil musste leider im 2. Semester ebenfalls aus dem Projekt, wegen Krankheit, ausscheiden.


|===
| Name| Rolle WS 21/22 | Rolle SoSe 22 | E-Mail

| Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
| Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
| Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
| Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
| Jonas Keil | Implementation | aus Projekt ausgeschieden | s81910@htw-dresden.de
| Carl Kirchhoff | Architektur | Architektur | s82087@htw-dresden.de
| Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
| Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
| Vinh Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
|===

===  Kommunikation und eingesetzte Tools

Unsere interne Teamkommunikation ist größtenteils gleich wie im 1. Semester.
Für unseren wöchenlichen Gruppentreffen am Montagsabend verwendeteten wir Disord, da es einfach zu benutzen war und wertvolle Funktionen hat, wie Bildschirmübertragung und einen simplen File-Upload.
Wir verwendeten zusätzlich WhatsApp, um schneller Antworten für organisatorische Angelegenheiten erhalten zu können. Discord und Whatsapp wurden auch verwendet, wenn Mitglieder zusammen an einer Aufgabe gearbeitet haben oder ein Hilfe bei einem Problem benötigten.
In der zweiten Hälfte des des 2. Semester haben wir auch Pull-Requests bei GitHub eingesetzt, wo direkt Feedback gegeben werden konnte.

Bei der Kommunikation wurde im Vergleich zum 1. Semester wurde mit dem Themensteller bloß noch über Discord kommuniziert und nicht noch zusätzlich über Mail. Über Discordprivatnachrichten wurden Termine für Treffen abgesprochen und die Termine selbst über den Discordserver im Sprachchat, wo teilweise auch die Bildschirme übertragen wurden sind.



===  Dokumenation und eingesetzte Tools 

//wenn dokumentation zu ernst genommen wird, dann passt hier docker und mariadb etc nicht hin
//    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge), draw.io


Unsere Dokumenation wurde persistent auf GitHub gepeichert, wo auch der Code lag. Dort wurden auch die mit anderen Tools erstellten Grafiken hochgeladen. Diese Grafiken wurden mit Draw.io und VisualParadigm erstellt und als Foto in die Dokumenation geladen. 
// gibt es noch anderen grafiktools?
Die Meetings mit Herrn Liebert wurden auf gemeinsamen GoogleDocs-Dokumenten vor- und nachbereitet, da diese von jedem Teammitglied parallel bearbeitet werden kann. Ebenso haben wir bei GoogleDocs ein Excelsheet verwendet, wo unsere ungefähren Arbeitszeiten auf Vertrauensbasis aufgeschrieben wurden, damit geschaut werden kann, dass jeder ungefähr gleich viel Zeit in das Projekt steckt.



===  Techniken/Praktiken - Way of Working

////
 //// 

Kommunikation
        Team: Whatsappgruppe für nicht aufgaben -> spontane absprachen, terminfindung
                discord für gruppenmeeting 
                discord/whatsapp für fragen bzw zusammenarbeit von aufgaben
                github comments bei commits/pull request für verbesserungen und fragen/antworten

        Auftraggeber: für die kommunikation wurde im 1. semester email zur verabredung und kleinen fragen genutzt
        zur "face-to-face" kommunkikation, u.a. wie die anwendung gestaltet werden soll und andere organisatorische fragen
        da helena die email hatte und nick, nicht warten/suchen wollte, hat der komplette kontakt über discord stattgefunden
    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge), draw.io








Aufgabenstellung:
erstellung einer kalenderanwendung. dort kann eingetragen werden, welche Projekte an den tagen geplant sind
es soll möglich sein, mitarbeiter anzulegen und zu löschen
projekte sollen erstellbar sein und löschbar (beendet), den projekten sollen mitarbeiter hin- und entfernt können
es soll eine funktion geben, wo feiertage eingetragen werden können. über eine API und manuell
Auftraggeber:
T- Systems MMS
Ausgangssituation zum Semesterbeginn:

- keine gruppe hat vorgearbeitet -> konnten auf nichts aufbauen


//passt das hier überhaupt hin?
niclas hatte als einziger viel erfahrung mit coden und wie man sachen am besten macht
vitality, justus, carl und jonas hat etwas erfahrung im front end

helena, aleksandra und nick hattem mit dem "anwenden" keine erfahrung

Projektorganisiation:
    Team und Rollen/Veranwortlichkeiten:
    | Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
    | Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
    | Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
    | Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
    | Jonas Keil | Implementation | aus Projekt ausgeschieden | s81910@htw-dresden.de
    | Carl Kirchhoff | Architektur | Architektur | s82087@htw-dresden.de
    | Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
    | Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
    | Vinh Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
    Kommunikation
        Team: Whatsappgruppe für nicht aufgaben -> spontane absprachen, terminfindung
                discord für gruppenmeeting 
                discord/whatsapp für fragen bzw zusammenarbeit von aufgaben
                github comments bei commits/pull request für verbesserungen und fragen/antworten

        Auftraggeber: für die kommunikation wurde im 1. semester email zur verabredung und kleinen fragen genutzt
        zur "face-to-face" kommunkikation, u.a. wie die anwendung gestaltet werden soll und andere organisatorische fragen
        da helena die email hatte und nick, nicht warten/suchen wollte, hat der komplette kontakt über discord stattgefunden
    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge)


