= Planung

== Ausgangssituation in Software Engineering II

===  Auftraggeber und Aufgabenstellung

Im Rahmen des Moduls "Software Engineering II" haben wir die Aufgabe erhalten eine Ressourcenverwaltung in Kalenderform für T-Systems MMS zu entwickeln. Unser Ansprechpartner in der Firma war Herr Sven Liebert und in der HTW Dresden waren es Herr Zirkelbach als Coach und Herr Prof. Anke als Dozent.

Die Anwendung stellt in einer Kalenderansicht dar, woran der Benutzer an diesem Tag aktuell arbeitet bzw. gearbeitet hat.
Dafür können Projekte und Benutzer erstellt werden. Jeder Benutzer soll Projekte und andere Benutzer erstellen, bearbeiten und löschen können. Die Benutzer können ebenfalls zu Abteilungen zugeordnet werden. 
Es gibt keine unterschiedlichen Berechtigungen. Jeder darf jede Funktion ausführen. 

Feiertage und Betriebsferien sollen ebenfalls dargestellt werden. Für die Feiertage wird eine spezielle API verwendet. Die Betriebsferien bzw. Bundesland abhängige Feiertage sollen "per Hand" erstellt werden können.

Es gibt die technische Vorausetzung, dass das System auf Docker und als Webanwendung betrieben werden kann. Andere Bedingungen sind nicht gegeben.

===  Situation zum Semesterbeginn

Unser Team hat bereits letztes Semester an diesem Projekt gearbeitet. Daher haben wir dank guter Vorarbeit eine Dokumentation, welche bereits auf einem guten Stand war und lediglich kleine Verbesserungen benötigte. 
Mit Entwicklung der Anwendung haben wir im vorangegangenen Semester ebenfalls begonnen. Große Teile des Front-Ends waren auch schon funktional erstellt. Es fehlte z.B. noch die Seite für die Projekterstellung und der Feiertags-Import Funktion.
Wenige grundlegende Back-End-Strukturen und -funktionen waren auch schon angelegt, wie z.B. die Datenbank und das Anzeigen von Mitarbeitern in der Kalenderansicht.

Unsere Arbeitsmoral war aufgrund guter Leistungen im vorangegangenen Semester ziemlich hoch. Jedoch wussten wir, dass die bevorstehenden Aufgaben schwer werden könnten, da es einiges neues Wissen zu erlernen galt. Dies gilt besonders für unsere Programmierkenntnisse. 
Teamleiterin Frau Rubein hat uns, wie geplant, verlassen.

===  Team und Rollen

Unsere Rollen bzw. Verantwortlichkeiten wurden aus dem vorangegangenen Semester übernommen. Dort wurden diese so weit wie möglich nach bereits vorhandener Kompetenz vergeben. Dies trifft auf Herrn Werner, Herrn Beck, Herrn Tichonow und später auch auf Herrn Nguyen zu. Frau Rubein, Frau Tartz, Herr Kemter, Herrn Keil und Herr Kirchhoff mussten sich ihre Kompetenz erst erarbeiten und haben daher Rollen erhalten, welche mit ihren bisherigen Stärken und Interessen die größte Schnittmenge hatten. 

Aus den ursprünglichen acht Mitgliedern wurden im 2. Teil des Projekts noch sieben, da Frau Rubein Wirtschaftsingenieurin ist und damit Software-Engineering II nicht mehr belegt. Die Teamleitung hat Herr Kemter übernommen. Unser Team bekam nach wenigen Wochen Herr Nguyen als Nachzügler zur Unterstützung. Dieser hatte bereits Programmiererfahrungen und bekam daher die Verantwortung der Implementation. Herr Keil musste leider, wegen Krankheit, im 2. Semester ebenfalls aus dem Projekt ausscheiden. 

|===
| Name| Rolle WS 21/22 | Rolle SoSe 22 | E-Mail

| Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
| Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
| Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
| Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
| Jonas Keil | Implementation | aus Projekt ausgeschieden | s81910@htw-dresden.de
| Carl Kirchhoff | Architektur | Architektur | s82087@htw-dresden.de
| Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
| Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
| Vinh Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
|===

===  Kommunikation und eingesetzte Tools

Unsere interne Teamkommunikation ist gleich geblieben.
Für unseren wöchenlichen Gruppentreffen am Montagsabend verwendeten wir Discord, da es einfach zu benutzen war und wertvolle Funktionen hat, wie Bildschirmübertragung und einen simplen File-Upload.
Wir verwendeten zusätzlich WhatsApp, um schnelle Antworten für organisatorische Angelegenheiten erhalten zu können. 
Discord und WhatsApp wurden auch verwendet, wenn Mitglieder zusammen an einer Aufgabe gearbeitet haben oder Hilfe bei einem Problem benötigten.

In der zweiten Hälfte des Semesters haben wir Pull-Requests bei GitHub eingesetzt, wodurch direkt Feedback zu erstellten Inhalten gegeben werden konnte.

Im Vergleich zum vorherigen Semester wurde mit dem Themensteller über Discord via Discordprivatnachrichten kommuniziert und nicht zusätzlich über E-Mail. Die Meetings fanden über den Discordserver im Sprachchat statt, wo häufig auch die Bildschirme übertragen wurden.

===  Dokumentation und eingesetzte Tools 
Unsere Dokumentation und Code wurde persistent auf GitHub gespeichert. 

Dort wurden auch die mit anderen Tools erstellten Grafiken hochgeladen. Diese Diagramme wurden mit Draw.io und VisualParadigm erstellt und zusätzlich PNG gesichert. 

Die Meetings mit Herrn Liebert wurden auf gemeinsamen Google Docs-Dokumenten vor- und nachbereitet, da diese von jedem Teammitglied parallel bearbeitet werden können. Ebenso haben wir bei Google Docs ein Excelsheet verwendet, wo unsere ungefähren Arbeitszeiten auf Vertrauensbasis aufgeschrieben wurden, damit geschaut werden kann, dass jeder ungefähr gleich viel Zeit in das Projekt investiert.

===  Techniken/Praktiken - Way of Working

Die Arbeitsweise orientierte sich am Open Unified Process. Das Team bemühte sich, die vier Eigenschaften zu erfüllen. Ebenfalls haben wir versucht, andere Praktiken und eigene Erfahrungen einzubringen. Die Projektstrategie haben wir nach dem Kunden und seinen Bedürfnissen ausgerichtet. Der Fokus wurde auf eine offene, direkte Kommunikation und eine learning-by-doing Mentalität gelegt.
Es wurde in einwöchigen Iterationen gearbeitet, diese setzten ein hohes Maß an Eigenverantwortung und Selbstmanagement voraus.
Der Ablauf setzte sich aus folgenden Punkten zusammen:

==== Planung der Iteration

Die Iterationplanung erfolgte Kundenorientiert. Offene Aufgaben wurden nach Priorität geordnet und vorbereitet, draus entstandene Aufwandsabschätzung wurde gemeinsam im Team besprochen. Die Aufgaben wurden nach Fachkenntnis/Fähigkeiten verteilt.

==== Durchführen der Iteration

Die Aufgaben wurden selbstständig abgearbeitet. Durch Pullrequests haben wir uns über Fortschritte oder Hindernisse informiert, diese dann überprüft und gegebenenfalls die Teamarbeit modifiziert, indem ein Problem zu zweit besprochen wurde.

==== Bewertung der Iteration

In einem Teammeeting wurde die erledigte Aufgabe vorgestellt. Durch das Feedback der Teammitglieder konnten weitere Verbesserungen vorgenommen werden. In jeder Iteration wurde erfasst, welche Aufgaben fertig gestellt wurden oder noch offen blieben. Offene Aufgaben oder Ergänzungen wurden in die nächste Iteration übernommen. In solchen Fällen musste die Aufwandsabschätzung erneut bewertet werden.