//verwende glaube immer unterschiedliche und falsche zeitformen
= Planung

== Ausgangssituation in Software Engineering II

===  Auftraggeber und Aufgabenstellung

Im Rahmen des Moduls "Software Engineering II" haben wir die Aufgabe erhalten eine Ressourcenverwaltung in Kalenderform für T-Systems MMS zu entwickeln. Unser Ansprechpartner in der Firma war Herr Sven Liebert und in der HTW Dresden waren es Herr Zirkelbach als Coach und Herr Prof. Anke als Dozent.

Die Anwendung stellt in einer Kalenderansicht dar woran der Benutzern an diesen Tag plant zu arbeiten bzw. gearbeitet hat.
Dafür können Projekte und Benuter erstellt werden. Jeder Benutzer soll Projekte und andere Benuter erstellen und bearbeiten bzw. löschen können. Die Benuter können ebenfalls zu Abteilungen zugeordnet werden. 
Jeder Benutzer darf jede Funktion ausführen. Es gibt keine unterschiedlichen Berechtigungen. 

Feiertage und Betriebsferien sollen über ebenfalls dargestellt werden. Für die Feiertage wird eine spezielle API verwendet. Für die Betriebsferien bzw. Bundesland abhängige Feiertage sollen diese Tage "per Hand" erstellt werden können.

Es gibt die technische Vorrausetzung, dass das System auf Docker und als Webanwendung betrieben werden kann. Andere Bedingungen sind nicht gegeben.

===  Situation zum Semesterbeginn

Unser Team hat bereits letztes Semester an diesem Projekt gearbeitet. Daher haben wir dank guter Vorarbeit eine Dokumentation, welche bereits auf einem guten Stand war und ledeglich kleine Verbesserungen benötigte. 
Die Anwendung selbst war auch auch begonnen. Große Teile des Front-Ends waren auch schon funktional erstellt. Es fehlte z.B. noch die Seite für die Projekterstellung und der Feiertags-Import Funktion.
Wenige Grundlegende Back-End-Strukturen und -funktionen waren auch schon angelegt, wie z.B. die Datenbank und das anzeigen von Mitarbeitern in der Kalenderansicht.

Unsere Arbeitsmoral war aufgrund guter Leistungen im vorangegangenen Semester ziemlich hoch. Jedoch wussten wir, dass die bevorstehenden Aufgaben schwer werden könnten, da es einiges neues Wissen zu erlernen galt. Dies gilt besonders für unsere Programmikenntnisse. 
Teamleiterin Frau Rubein hat uns, wie geplant, verlassen.

===  Team und Rollen

Unsere Rollen bzw. Verantwortlichkeiten wurden aus dem vorherigen Semester übernommen. Dort wurden diese soweit wie möglich nach bereits vorhandener Kompetenz vergeben. Dies trifft auf Herrn Werner, Herrn Beck, Herrn Tichonow und später auch auf Herrn Nguyen zu. Frau Rubein, Frau Tartz, Herr Kemter, Herrn Keil und Herr Kirchhoff mussten sich ihre Kompetenz erst erarbeiten und haben daher Rollen erhalten, welche mit ihren bisherigen Stärken und Interessen die größte Schnittmenge hatten. 

Aus den ursprünglichen acht Mitgliedern wurden im 2. Teil des Projekts bloß zwischenzeitlich noch sieben, da Frau Rubein Wirtschaftsingeneurin ist und damit Software Engineering II nicht mehr belegt. Da Frau Rubein die Teamleitung inne hatte, hat Herr Kemter die Rolle übernommen. Jedoch bekam unser Team nach wenigen Wochen Herr Nguyen als Nachzügler in unser Team. Dieser hatte bereits Programmiererfahrungen und bekam daher die Verantwortung der Implementation erhalten. Herr Keil musste leider, wegen Krankheit, im 2. Semester ebenfalls aus dem Projekt ausscheiden. 


|===
| Name| Rolle WS 21/22 | Rolle SoSe 22 | E-Mail

| Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
| Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
| Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
| Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
| Jonas Keil | Implementation | aus Projekt ausgeschieden | s81910@htw-dresden.de
| Carl Kirchhoff | Architektur | Architektur | s82087@htw-dresden.de
| Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
| Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
| Vinh Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
|===

===  Kommunikation und eingesetzte Tools

Unsere interne Teamkommunikation ist größtenteils gleich wie im Semester davor.
Für unseren wöchenlichen Gruppentreffen am Montagsabend verwendeteten wir Discord, da es einfach zu benutzen war und wertvolle Funktionen hat, wie Bildschirmübertragung und einen simplen File-Upload.
Wir verwendeten zusätzlich WhatsApp, um schnelle Antworten für organisatorische Angelegenheiten erhalten zu können. 
Discord und Whatsapp wurden auch verwendet, wenn Mitglieder zusammen an einer Aufgabe gearbeitet haben oder Hilfe bei einem Problem benötigten.

In der zweiten Hälfte von diesem Semester haben wir auch Pull-Requests bei GitHub eingesetzt, wodurch direkt Feedback zu dem erstellten Inhalten gegeben werden konnte.

Bei der Kommunikation wurde im Vergleich zum vorherigen Semester wurde mit dem Themensteller über Discord kommuniziert und nicht noch zusätzlich über E-Mail. Über Discordprivatnachrichten wurden Termine für Treffen abgesprochen und die Termine selbst über den Discordserver im Sprachchat, wo häufig auch die Bildschirme übertragen wurden sind.

===  Dokumenation und eingesetzte Tools 
//wenn "dokumentation" zu ernst genommen wird, dann passt hier docker und mariadb etc nicht hin
//    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge), draw.io
Unsere Dokumenation und Code wurde persistent auf GitHub gepeichert. 

Dort wurden auch die mit anderen Tools erstellten Grafiken hochgeladen. Diese Diagramme wurden mit Draw.io und VisualParadigm erstellt und zusätzlich PNG gesichert. 

Die Meetings mit Herrn Liebert wurden auf gemeinsamen GoogleDocs-Dokumenten vor- und nachbereitet, da diese von jedem Teammitglied parallel bearbeitet werden können. Ebenso haben wir bei GoogleDocs ein Excelsheet verwendet, wo unsere ungefähren Arbeitszeiten auf Vertrauensbasis aufgeschrieben wurden, damit geschaut werden kann, dass jeder ungefähr gleich viel Zeit in das Projekt invistiert.

===  Techniken/Praktiken - Way of Working


==== Planung der Iteration

In jeder Iteration wurde erfasst, welche wichtigen Aufgaben bzw. Funktionalitäten als nächstes realisiert werden sollten. Dazu zählen auch nicht fertiggestellte 

==== Durchführen der Iteration

==== Bewertung der Iteration

////
 //// 

Kommunikation
        Team: Whatsappgruppe für nicht aufgaben -> spontane absprachen, terminfindung
                discord für gruppenmeeting 
                discord/whatsapp für fragen bzw zusammenarbeit von aufgaben
                github comments bei commits/pull request für verbesserungen und fragen/antworten

        Auftraggeber: für die kommunikation wurde im 1. semester email zur verabredung und kleinen fragen genutzt
        zur "face-to-face" kommunkikation, u.a. wie die anwendung gestaltet werden soll und andere organisatorische fragen
        da helena die email hatte und nick, nicht warten/suchen wollte, hat der komplette kontakt über discord stattgefunden
    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge), draw.io








Aufgabenstellung:
erstellung einer kalenderanwendung. dort kann eingetragen werden, welche Projekte an den tagen geplant sind
es soll möglich sein, mitarbeiter anzulegen und zu löschen
projekte sollen erstellbar sein und löschbar (beendet), den projekten sollen mitarbeiter hin- und entfernt können
es soll eine funktion geben, wo feiertage eingetragen werden können. über eine API und manuell
Auftraggeber:
T- Systems MMS
Ausgangssituation zum Semesterbeginn:

- keine gruppe hat vorgearbeitet -> konnten auf nichts aufbauen


//passt das hier überhaupt hin?
niclas hatte als einziger viel erfahrung mit coden und wie man sachen am besten macht
vitality, justus, carl und jonas hat etwas erfahrung im front end

helena, aleksandra und nick hattem mit dem "anwenden" keine erfahrung

Projektorganisiation:
    Team und Rollen/Veranwortlichkeiten:
    | Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
    | Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
    | Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
    | Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
    | Jonas Keil | Implementation | aus Projekt ausgeschieden | s81910@htw-dresden.de
    | Carl Kirchhoff | Architektur | Architektur | s82087@htw-dresden.de
    | Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
    | Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
    | Vinh Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
    Kommunikation
        Team: Whatsappgruppe für nicht aufgaben -> spontane absprachen, terminfindung
                discord für gruppenmeeting 
                discord/whatsapp für fragen bzw zusammenarbeit von aufgaben
                github comments bei commits/pull request für verbesserungen und fragen/antworten

        Auftraggeber: für die kommunikation wurde im 1. semester email zur verabredung und kleinen fragen genutzt
        zur "face-to-face" kommunkikation, u.a. wie die anwendung gestaltet werden soll und andere organisatorische fragen
        da helena die email hatte und nick, nicht warten/suchen wollte, hat der komplette kontakt über discord stattgefunden
    eingesetzte Tools: discord, whatsapp, docker(?), github, vs code, mariadb, google docs (für gemeinsame dokumente und zeitplan), psalm (und die anderen github dinge)


