//AKTUELL SIND ES NUR STICHPUNKTE/GEDANKENSTÜTZEN WAS HIER BEHANDELT WERDEN SOLL


//wie zweites beispiel auf seiner folie -> für jeden geforderten aspekt einen kleinen bericht

= Ergebnisse

== Was haben wir erreicht?
Wir haben es erreicht, dass jeder Benutzer einen eigenen Account hat. Das mag im Moment noch etwas unnötig klingen, da jeder Benutzer alles machen kann. Jedoch stellt es für eine eventuelle Weiterentwicklung eine gute Basis dar. Weiterhin können die Benutzer Projekte erstellen und neue Mitarbeiter bzw. Benutzer erstellen. Die Benutzer können sich dann diese Projekte als Stati in der für jeden Wochentag eintragen. Die Stati können logischerweise wieder entfernt werden, denn was wäre eine Ressourcenverwaltung-Anwendung, wenn nicht auf geänderte Pläne reagiert werden kann? Außerdem können die Projekte und die Benutzer gelöscht werden. Leider kann man die Benutzer und Projekte nach der Erstellung nicht bearbeiten -> Probleme bei Heirat oder auscheiden eines Benutzers, dann hat ein Projekt kein Verantwortlichen  
Die Kalenderansicht ist in der Lage von der aktuellen Kalenderwochde beliebig viele Wochen vor- und zurückgehen und dabei die Daten und die eingetragenen Stati anzeigen kann.
Aufgrund von zu wenig Zeit haben wir es nicht geschafft, dass man aus einer anderen Woche die Stati in eine andere Woche übernehmen kann. 
Wir konnten ebenfalls keine Feiertage zu implementieren. Dort sollten wir über die Feiertags-API, aber auch Manuell, Feiertage in das Programm laden. An diesen Tagen, kann dann kein Benuter einen Stati anlegen. Da hier auch viele neue visuelle Elemente erstellt hätten müssen, hätten wir noch mehrere Iterationen gebraucht.
Einige "Features" wurden angefangen jedoch haben sie am Ende keinen Sinn, da mit ihnen nichts gemacht wird (aber tbh kam da auch nicht wirklich viel vom TS was damit geplant ist)

-> die "nicht geschafft" mit zu wenig zeit und eventueller wenig arbeit von 2 leiten... 
eventuell hätte man noch mehr geschafft, jedoch wollten wir die zeit eher in die doku stecken

die wichtigsten UC / Funktionen wurden erreicht die für eine benutzung der anwendung nötig sind
-> sollen die use cases nochmal beschrieben werden und was damit gemacht werden kann?


einige alternativabläufe wurden nicht erfüllt. diese sind jedoch (aus unserer sicht nice to have), da der bearbeiten zumindest auch über löschen und neu erstellen möglich ist. 
das übernehmen von stati aus der einen woche in eine andere wurde nicht erfüllt, obwohl es eigentlich ein nützliches feature wäre

ein kompletter use case #5 wurde nicht erfüllt, da dafür keine zeit. mit einigen wochen mehr, wäre es vermutlich etwas geworden 
die gründe für das nicht erfüllen waren als primärgrund keine zeit. genauer war es aber, dass am anfang vermutlich einfach nicht genug gemacht wurde. am ende wollten wir die restliche zeit in die dokumente reinstecken

=== Reflexion der Teammitglieder