//AKTUELL SIND ES NUR STICHPUNKTE/GEDANKENSTÜTZEN WAS HIER BEHANDELT WERDEN SOLL


//wie zweites beispiel auf seiner folie -> für jeden geforderten aspekt einen kleinen bericht

= Ergebnisse

== Was haben wir erreicht?

die wichtigsten UC / Funktionen wurden erreicht die für eine benutzung der anwendung nötig sind
-> sollen die use cases nochmal beschrieben werden und was damit gemacht werden kann?


einige alternativabläufe wurden nicht erfüllt. diese sind jedoch (aus unserer sicht nice to have), da der bearbeiten zumindest auch über löschen und neu erstellen möglich ist. 
das übernehmen von stati aus der einen woche in eine andere wurde nicht erfüllt, obwohl es eigentlich ein nützliches feature wäre

ein kompletter use case #5 wurde nicht erfüllt, da dafür keine zeit. mit einigen wochen mehr, wäre es vermutlich etwas geworden 
die gründe für das nicht erfüllen waren als primärgrund keine zeit. genauer war es aber, dass am anfang vermutlich einfach nicht genug gemacht wurde. am ende wollten wir die restliche zeit in die dokumente reinstecken

=== Reflexion der Teammitglieder