= Ergebnisse

== Bewertung


Wir haben erreicht, dass jeder Benutzer einen eigenen Account hat. Das mag im Moment noch etwas unnötig klingen, da jeder Benutzer alles machen kann. Jedoch stellt es für eine eventuelle Weiterentwicklung eine gute Basis dar. Weiterhin können die Benutzer Projekte erstellen und neue Benutzer erstellen. Die Benutzer können sich dann diese Projekte als Status in der für jeden Wochentag eintragen. Die Status können wieder entfernt werden. Außerdem können die Projekte und die Benutzer gelöscht werden. Leider können die Benutzer nach der Erstellung nicht bearbeitet werden. Bei Projekten ist lediglich das Hinzufügen/Entfernen der beteiligten Benutzer möglich. Das wird allerdings problematisch, sobald ein Benutzer gelöscht werden soll, der auch Projektverantwortlicher ist. Da nun auch jedes Projekt gelöscht wird, für das dieser Benutzer verantwortlich ist. Die Ursache besteht darin, dass jedes Projekt einen Verantwortlichen benötigt und eine Neuzuweisung ist aktuell nicht möglich. Ebenso kann es ein Problem bei Heirat der Benutzer geben, wenn diese plötzlich anders heißen. Ein ähnliches Problem tritt auf, wenn sich beispielsweise der Nachname eines Benutzers ändert - da auch dieser nicht nachträglich bearbeitet werden kann.

Des Weiteren ist es möglich, vergangene und kommende Kalenderwochen anzeigen zu lassen. Es ist nicht möglich, die Status aus einer Woche in eine andere Woche zu übernehmen. 

Wir konnten es ebenfalls nicht realisieren, Feiertage in irgendeiner Art und Weise zu implementieren. Da hier auch viele neue visuelle Elemente hätten erstellt werden müssen, wären noch mehrere Iterationen nötig gewesen.

Einige andere und kleine Funktionalitäten, wie zum Beispiel die Status mit Farben anzeigen, wurde ebenfalls nicht realisiert. Diese wurden hinten angestellt, da es andere Funktionalitäten gab, welche eine größere Wichtigkeit hatten. Außerdem hätten noch verschiedene andere Effekte, die der Anwendung mehr Interaktion mit bzw. Feedback für den Nutzer verliehen hätten, programmiert werden können - beispielsweise wie die Farbänderung beim Hovern mit dem Mauszeiger über einen Button. 


Am Ende kann gesagt werden, dass die nicht geschafften Use Cases und Funktionalitäten wegen zu wenig Zeit nicht erfüllt worden sind. Die Fähigkeiten der Programmierer, besonders bei Herrn Werner und Herrn Nguyen, reichten für die Implementierung aus. Dies war auch hilfreich, da sie Hilfestellung für jene geben konnten, die nicht so viel Können mitbrachten.

Des Weiteren war uns eine möglichst gleichmäßige Arbeitsverteilung wichtiger, als die Erfüllung aller Forderungen, um somit den Lerneffekt für alle Beteiligten so groß wie möglich zu halten und dass kein Mitglied sich überarbeitet.
Dennoch vielen die Mengen der übernommenen Aufgaben, teils wegen Krankheit, unterschiedlich aus. Was am Ende auch der Hauptgrund für das oben beschriebene Nichterfüllen mancher Anforderungen ist.

Durch Unachtsamkeit wurde die Bezeichnung "Mitarbeiter" mehrfach in der Anwendung und auch im Sourcecode verwendet. Die richtige Bezeichnung ist "Benutzer". Vermutlich hat dies keinen negativen Einfluss auf die Anwendung und deren Nutzen, könnte jedoch bei einer eventuellen Weiterentwicklung zuerst zu Verwirrung und zu etwas Arbeit beim Berichtigen führen.