= Projektplan: {project-name}
Helena Rubein <s81097@htw-dresden.de>; Nick Kemter <s82068@htw-dresden.de>; Justus Beck <s82023@htw-dresden.de>; Niklas Werner <s82076@htw-dresden.de>; Jonas Keil <s81910@htw-dresden.de>; Carl Kirchhoff <s82087@htw-dresden.de>; Aleksandra Tartz <s80433@htw-dresden.de>; Vitali Tichonow <s82591@htw-dresden.de>; Ving Nguyen <s77261@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Einführung
//Briefly describe the content of the project plan.
Der Projektplan gibt einen Überblick über das Projekt E1_Ressourcenverwaltung. Dabei werden Meilensteine definiert und terminiert. Zudem wird in diesem Projektplan die gesamte Projektorganisation beschreiben. 

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.

//passt die Tabelle so? verschiedene Rollen zu verschiedenen Zeiten

|===
| Name| Rolle WS 21/22 | Rolle SoSe 22 | E-Mail

| Helena Rubein | Teamleiterin und Analyst | aus Projekt ausgeschieden | s81097@htw-dresden.de 
| Nick Kemter | Test | Teamleiter und Test | s82068@htw-dresden.de 
| Justus Beck | Implementation | Implementation | s82023@htw-dresden.de 
| Niklas Werner | Architektur | Architektur | s82076@htw-dresden.de 
| Jonas Keil | Implementation | Implementation | s81910@htw-dresden.de
| Carl Kirchhoff | Architektur | Architekture | s82087@htw-dresden.de
| Aleksandra Tartz | Analyst | Analyst | s80433@htw-dresden.de
| Vitaly Tichonow | Test | Test | s82591@htw-dresden.de
| Ving Nguyen | noch nicht Teil des Projekts | Implementation | s77261@htw-dresden.de
|===

Die Kommunikation innerhalb des Teams findet auf mehreren Wegen statt. Themen über die schnell abgestimmt werden müssen, werden in einer WhatsApp-Gruppe diskutiert, da jedes Teammitglied diesen Channel schnell zur Verfügung hat. Ausführlichere Themen werden über einen Discordchannel besprochen. Zudem ist jede Woche Montag um 17 Uhr ein Teammeeting angesetzt, um über den Stand des Projektes, die erledigten Aufgaben und die anstehenden Aufgaben zu sprechen. Meistens sind alle Teammitglieder bei diesen Meetings anwesend. Alle Meetingprotokolle werden über Googledrive für alle Mitglieder zur Bearbeitung freigegeben. 

Wir pflegen in unserem Team einen respektvollen Umgang miteinander. Alle Probleme werden offen kommuniziert. Außerdem achten wir auf eine gleichmäßige Arbeitsverteilung. Um das nachzuvollziehen, trägt jedes Teammitglied am Ende einer Iteration seine/ihre benötigte Arbeitszeit ein. 

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).
// https://www2.htw-dresden.de/~anke/openup/index.htm
=== Praktiken 
- Iterative Entwicklung

Zu Anfang jeder Iteration (14-tägig) werden Aufgaben an die einzelnen Teammitglieder vergeben, welche bis zur nächsten Iteration im angemessenen Maße bearbeitet werden sollen. Die Aufgaben sind normalerweise kleine Teilfunktionen der Webanwendung. 
//funktionszuwachs??
Wöchentlich wird der Stand des Projektes in den Teammeetings abgeglichen. Dadurch kann sich ein Überblick beendeten Aufgaben und deren Bewertung verschafft werden. Die Iterationslängewurde am Anfang des Projekts auf eine Woche festgelegt. In der zweiten Hälfte des Projekts wurde es auf zwei Wochen angehoben.
Die Größe der Aufgaben wird in T-Shirt-Größen angegeben. 

- Whole Team

Auch wenn jedes Teammitglied einzelne Aufgaben in seinem "Expertengebiet" erledigt, ist das ganze Team dafür verantwortlich, dass alle Aufgaben korrekt erfüllt werden.
Wenn ein Teammitglied ein Problem hat, kann es andere Teammitglieder um Hilfe fragen. Ebenso darf jeder zu den wöchentlichen Teammeetings seine Meinung und Kritik äußern.
Die verteilten Aufgaben und ihr Fertigungsstellungsdatum sind angemessen gewählt, so dass sich niemand überarbeitet.
Das Team und der Themensteller soll mit Vision ein gemeinsames Verständnis für das Projekt entwickeln und sich konkret darauf einigen 


- Risk-Value Lifecycle 

Unser Projekt wird in vier grobe Projektphasen unterteilt. Jede Phase hat einen anderen Schwerpunkt bei der Entwicklung des Projekts. Dadurch können Risiken besser eingeschätzt werden, ebenso ob das Projekt fortgeführt werden sollte.


- Concurrent Testing 

Concurrent Testing wird bei uns im Team angewendet. Jedoch werden im Moment noch keine automatisierten Tests verwendet. Aktuell wird der Programmcode mit einer Testliste verglichen. Units-Test sind noch geplant. 
Es ist geplant, dass vorallem Herr Kemter und ??? die Test planen und ausführen.

- Use Case Driven Development 

In den ersten Iterationen wurde ein Use Case Model mit ausgearbeiteten Use Cases erstellt. Diese dienen dazu, dass wir ein besseres Verständnis der zu erstellenden Funktionen zu erhalten. 
Ebenso wurde ein Dokument mit den verschiedenen Requirements erstellt. Dies dient dazu, dass Anforderungen nicht vergessen werden und möglichst genau beschrieben werden.
Durch die priorosierte Bearbeitung von einem Use-Case wird versucht immer einen Funktionszuwachs in der Iteration bzw. bei Issues zu erhalten.

=== Qualitätssicherung

Jedes Teammitglied bekommt jede Iteration, je nach Aufwand, ein oder manchmal auch zwei Issues bei Github zugeteilt. Wenn es ein Implementation-Issue war, dann stellt zuerst das Teammitglied, was den Issue bearbeitet hat, sicher, dass es seine Funktion erfüllt und keine anderen Funktionen beeinträchtigt bzw. Bugs verursacht. Wenn das Issue "gepushed" wurde, soll jedes andere Teammitglied, was die Fähigkeiten hat, dies ebenfalls überprüfen. Bei dem wöchentlichen Treffen hat Herr Werner hat oftmals kleine Verbesserungsvorschläge für den Quellcode, wenn dort Kleinigkeiten besser gemacht werden können. Diese Vorschläge werden dann meist noch schnell umgesetzt. 

Issues, die kein hundertprozentig "richtig" haben, wie die Vision, Use Cases oder Architecture Notebook, werden meistens zu zweit bearbeitet. Dadurch soll sichergestellt werden, dass es direkt bei dem Erstellen zu einem Meinungsaustausch und Verbesserungen kommen kann. Sobald es gepushed wurde, soll jedes Teammitglied sich die erstellte Dokumentation anschauen und mögliche Verbesserungsvorschläge notieren. Bei dem nächsten Teammeeting werden diese angesprochen und eventuell umgesetzt. Ebenfalls können die ursprünglichen Ersteller dort noch Unsicherheiten, offene Fragen etc. ansprechen und ein Feedback erhalten. 

=== Bewertung
//hier ist das große ganze gemeint
//iterationsziel erfüllt?
Wenn viele neuer Funktionszuwachs stattgefunden hat, aber auch bevor und nachdem wichtige Funktionen für Use-Cases hinzugefügt werden/wurden, wird der Themensteller konsultiert und seine Meinung dazu reflektiert. 

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase


[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
|
* Das Team verschafft sich einen ersten Überblick über das Projekt.
* Das Risiko von unklaren Rollen im Projekt und unklarer Zieldefinition wird verringert. 
| 29.11.21 - 05.12.21
| -

| I2
|
* Vision und Use Cases mit Wireframes werden entwickelt. 
* Die Risiken eines unzureichenden Entwurfes und einer falschen Zieldefinition werden stark limitiert. 
| 06.12.21 - 12.12.21
| -

| I3
|
* Use Cases, Vision und Wireframes werden nach Gespräch mit Themensteller überarbeitet.
* Dadurch wird das Risiko minimiert, dass der Kunde den Entwurf nicht akzeptieren könnte. 
| 13.12.21 - 19.12.21
| -

| I4
|
* Use Cases und Vision werden nach Anmerkungen von Herrn Zirkelbach fertiggestellt.
* Das Risiko von Missverständnissen oder Unklarheiten wird minimiert. 
| 20.12.21 - 26.12.21
| -

| I5
|
* Datenbanktabellen sollen angelegt und "Mitarbeiter hinzufügen"- Ansicht sollen implementiert werden.
* Das Risiko eines unvollständigen und fehlerhaften Systems wird dadurch verringert. 
| 27.12.21 - 09.01.22
| -

| I6
|
* Systemweite Anforderungen werden beschrieben, eine VM wird beantragen und Funktionserweiterungen der Software werden durchgeführt.
* Das Risiko fehlerhafter Funktionen wird reduziert. 
| 10.01.22 - 16.01.22
| - 

| I7
|
* Architecture Notebook und Domainmodell werden entwickelt.
* Unklare Strukturen der Software werden aufgedeckt und es wird ein Gerüst für die Software geschaffen. 
| 17.01.22 - 23.01.22
| - 

| I8
|
* Test Cases werden beschreiben und letzte Verbesserungen an den Dokumenten werden durchgeführt. 
* Das Risiko von Unklarheiten in der Projektstruktur wird minimiert und es wird eine Basis für die Weiterarbeit im nächsten Semester geschaffen.  
| 24.01.22 - 30.01.22
| - 

|I9
|
* Verbesserung bzw. Korrektur des Beleges hat begonnen
* Dadurch wird fehlerhafte bzw. unklare Dokumentation, die später eventuell zu Fehlern führen könnte, minimiert
* Erweiterung der Funktionen der Webanwendung
* Damit wird das Risiko eines nicht fertigen Systems minimiert
* Herr Keil und Frau Tartz sind Krank. In der Zeit können sie keine Aufgaben erfüllen
| 23.03.22 - 28.03.22
| - 

|I10
| 
* Verbesserung des Beleges weiterführen, insbesondere Architecture Notebook und Projekct Plan
* Dadurch wird weiterhin fehlerhafte bzw. unklare Dokumentation, die später eventuell zu Fehlern führen könnte, minimiert
* Erweiterung der Funktionen der Webanwendung
* Damit wird das Risiko eines nicht fertigen Systems minimiert
* Herr Keil und Frau Tartz sind Krank. In der Zeit können sie keine Aufgaben erfüllen
| 29.03.22 - 04.04.22
| -

|I11
|
* Verbesserung des Beleges weiterführen, insbesondere Architecture Notebook und Projekct Plan, da in Iteration davor nicht fertiggestellt
* Dadurch wird weiterhin fehlerhafte bzw. unklare Dokumentation, die später eventuell zu Fehlern führen könnte, minimiert
* Erweiterung der Funktionen der Webanwendung, um z.B. Passwortkriterien, Abteilungsdropdown und Suche 
* Damit wird das Risiko eines nicht fertigen Systems minimiert
* Herr Keil und Frau Tartz sind Krank. In der Zeit können sie keine Aufgaben erfüllen
| 05.04.22. - 11.04.22
| - 

|I12
|
* Aktualisierung bzw. Kontrolle des Belegs, u.a. Form und Formulierung, aber auch Dokumente wie Risikoliste
* Damit wird dafür gesorgt, dass die Dokumentation aktuell bleibt und eventuelle Ungenauigkeiten verbessert werden
//Name nachschlagen und in andere Dokumente eintragen
* Vinh wird als neues Teammitglied aufgenommen und in das Projekt eingeführt. Außerdem wird er als Person in den Beleg integriert 
* Die Funktionen der Webanwendung werden erweitert, u.a. anzeigen der aktuellen Kalenderwoche, Projekterstellung und Implementierung verschiedener Geschäftslogik 
|12.04.22-25.04.22
|-

|I13
|
* Aktualisierung bzw. Kontrolle des Belegs, u.a. Form und Formulierung, aber auch Dokumente wie Use Cases
* Die Funktionen der Webanwendung werden erweitert.
* Herr Keil und Frau Tartz sind Krank. In der Zeit können sie keine Aufgaben erfüllen. Herr Kemter hat die Aufgabe bekommen, zu klären wann beide wieder Einsatzfähig sind bzw. bei noch längerer Krankheit dies an Herrn Anke weiterzuleiten.
* Herr Kemter wird in HTML und CSS eingeführt. Außerdem macht er einen Termin mit Herrn Liebert
|26.04.22-09.05.22
|-
|===

== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Die Übergabe der Software an den Auftraggeber erfolgt über GitHub. 

== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.
Bei den ersten paar Teammeetings wurden alle Ergebnisse der Iteration ausführlich diskutiert und zusammen verbessert. Dadurch gingen die Meetings meist länger als eine Stunde, was die Arbeitsmoral schmälerte. Um in diesem Punkt mehr Effizienz zu erzielen, wurden dann nur noch Verbesserungsvorschläge unterbreitet und die verantwortliche Person hat die Änderungen selbstständig ausgeführt. 

Zu Beginn des Projektes wurden Aufgaben in den Meetings zugewiesen und die Verantwortlichkeit dann im Meetingprotokoll dokumentiert. Das stellte sich als unübersichtlich heraus und benachteiligte Personen, die nicht am Meeting teilnehmen konnten. Um diesen Ablauf zu verbessern, sind wir nach zwei Wochen dazu übergegangen, die anstehenden Aufgaben über GitHub Issues zu organisieren, was auch den Vorteil hat, dass sich jeder seine Aufgabe selbst aussuchen kann. 

Die Iteration von einer Woche waren im 2. Semester zu kurz und haben keinen wirklichen Fortschritt erbracht. Daher wurde die Iterationszeit auf zwei Wochen angehoben.

//vinh hatte dubioses VS Code plugin, was den ganzen Code umformatiert hatte -> mal besser ausformulieren und so etwas in risikoliste aufnehmen