= Risikoliste: {project-name}
Helena Rubein <s81097@htw-dresden.de>; Nick Kemter <s82068@htw-dresden.de>; Justus Beck <s82023@htw-dresden.de>; Niklas Werner <s82076@htw-dresden.de>; Jonas Keil <s81910@htw-dresden.de>; Carl Kirchhoff <s82087@htw-dresden.de>; Aleksandra Tartz <s80433@htw-dresden.de>; Vitali Tichonow <s82591@htw-dresden.de>; Ving Nguyen <s77261@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


In diesem Dokument sind die wesentlichen Risiken des Projekts aufgeführt.

== Attribute

Dabei werden folgende Attribute verwendet:

* *Typ*: Ressourcen, Geschäftlich, Technisch, Zeitlich
* *Auswirkung (IMP)*: Wert zwischen 1 (niedrig) und 5 (hoch), der die Auswirkungen auf das Projekt angibt, wenn das Risiko eintritt
* *Wahrscheinlichkeit (PRB)*: Prozentangabe für die Eintrittswahrscheinlichkeit des Risikos
* *Stärke (MAG)*: Produkt aus Auswirkung und Wahrscheinlichkeit (damit kann die Liste sortiert werden)

== Risiken

Die Risiken sind in folgender Tabelle: <<table_risks>> dargestellt. Das Datum des Dokuments oben gibt an, wann die Risikoliste zuletzt aktualisiert wurde.


// Die inkludierte csv-Datei "risks.csv" verwendet `;` Semmikolons als Trennzeichen. Achten Sie beim Export als csv-Datei auf das Angeben des entsprechenden Trennzeichens. Verwenden Sie stattdessen `,` Kommas, kann das Tabellenattribut `separator=` weggelassen werden oder muss entprechend angepasst werden.

// PDF-Export: Seite im Querformat
[.landscape]
<<<

// table risks
// alte werte mal überarbeiten -> evtl so, dass alte "durchgestrichen" werden, damit fortschritt erkennbar ist
[#table_risks]
.Risiken
[%header, format="csv", separator=","]
|===
include::risks.csv[]
|===

// PDF-Export: Seite zurück zum Hochformat
[.portrait]
<<<


