name: ESLint JavaScript Code Analyser

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install modules
      run: |
        npm init \
        npm install eslint --save-dev \
        npm init @eslint/config            
    - name: Run ESLint
      run: npx eslint "src/webserver/**" --ext .js,.jsx,.ts,.tsx
