name: ESLint JavaScript Code Analyser

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: |
        yarn init \
        yarn add eslint --dev \
        yarn create @eslint/config            
    - name: Run ESLint
      run: eslint "src/webserver/**" --ext .js,.jsx,.ts,.tsx
